"""Constants for the RWS waterinfo integration."""

DOMAIN = "waterinfo"

CONST_CODE = "code"
CONST_MEASUREMENT = "grootheid"
CONST_NAME = "plaats"
CONST_MEASUREMENT_DESCR = "grootheiddescr"
CONST_UNIT = "eenheid"
CONST_DESCR = "omschrijving"
CONST_LOCATION = "location"
CONST_X = "X"
CONST_Y = "Y"
CONST_PROPERTY = "hoedanigheid"
CONST_COORD = "coord"
CONST_PAREMETER_DESCR = "parameter_decr"

ATTR_LAST_DATA = "last_data"
ATTR_X = "X-coordinaat"
ATTR_Y = "Y-coordinaat"
ATTR_DESCR = "description"
ATRR_MEASUREMENT = "measurement"
ATTR_LOCATION = "location"
ATTR_LAST_UPDATE = "last_update"
