"""Locations for the RWS waterinfo integration."""
"""Generated 25-12-2025 21:40:43."""
"""Active only: True."""
"""With code: False."""

CONF_LOC_OPTIONS = [
    {"label": "A12", "value": "a12"},
    {"label": "Aa, Helmond", "value": "aa.helmond"},
    {"label": "Aadorp", "value": "aadorp"},
    {"label": "Aarle-Rixtel, Goorloop, Wilhelminakanaal", "value": "aarlerixtel.goorloop.wilhelminakanaal"},
    {"label": "Aarle Rixtel, Schabbert, beneden", "value": "aarlerixtel.schabbert.beneden"},
    {"label": "Aarle Rixtel, Schabbert, boven", "value": "aarlerixtel.schabbert.boven"},
    {"label": "Aarle Rixtel, Schabbert, inlaat", "value": "aarlerixtel.schabbert.inlaat"},
    {"label": "Aarle Rixtel, Schabbert, uitlaat", "value": "aarlerixtel.schabbert.uitlaat"},
    {"label": "Almen", "value": "almen"},
    {"label": "Almere, Hollandse brug", "value": "almere.hollandsebrug"},
    {"label": "Ameland, Nes", "value": "ameland.nes"},
    {"label": "Ameland, westgat", "value": "ameland.westgat"},
    {"label": "Ameland Westgat platform", "value": "amelandwestgat"},
    {"label": "Amerongen, beneden", "value": "amerongen.beneden"},
    {"label": "Amerongen, boven", "value": "amerongen.boven"},
    {"label": "Amsterdam, NDSM werf", "value": "amsterdam.ndsmwerf"},
    {"label": "Amsterdam, Schellingwouderbrug", "value": "amsterdam.schellingwouderbrug"},
    {"label": "Amsterdam, Surinamekade", "value": "amsterdam.surinamekade"},
    {"label": "Andijk", "value": "andijk"},
    {"label": "Arnemuiden Oranjeplaat", "value": "arnemuiden.oranjeplaat"},
    {"label": "Arnhem, Nederrijn", "value": "arnhem.nederrijn"},
    {"label": "Beek en Donk, Biezenloop", "value": "beekendonk.biezenloop"},
    {"label": "Beek en donk, sluis 6, beneden", "value": "beekendonk.sluis6.beneden"},
    {"label": "Beek en donk, sluis 6, boven", "value": "beekendonk.sluis6.boven"},
    {"label": "Beek en Donk, Sluis 6, inlaat", "value": "beekendonk.sluis6.inlaat"},
    {"label": "Beek En Donk Sluis6 kolk", "value": "beekendonk.sluis6.kolk"},
    {"label": "Beek en Donk, Sluis 6, uitlaat", "value": "beekendonk.sluis6.uitlaat"},
    {"label": "Belfeld, boven", "value": "belfeld.boven"},
    {"label": "Berkhout", "value": "berkhout"},
    {"label": "Berlicum Schijndelseloop", "value": "berlicum.schijndelseloop"},
    {"label": "Blaarthem, Dommel", "value": "blaarthem.dommel"},
    {"label": "Bommenede", "value": "bommenede"},
    {"label": "Borgsweer stuw", "value": "borgsweer.verbindingskanaal"},
    {"label": "Borssele", "value": "borssele"},
    {"label": "Borssele Windpark Alpha platform", "value": "borsselealpha"},
    {"label": "Botlek Geulhaven", "value": "botlek.geulhaven"},
    {"label": "Botlek Rozenburgsesluis Calandkanaal", "value": "botlek.rozenburgsesluis.calandkanaal"},
    {"label": "Breda", "value": "breda"},
    {"label": "Breskens, Handelshaven", "value": "breskens.handelshaven"},
    {"label": "Brouwersdam Brouwershavense Gat 2", "value": "brouwersdam.brouwershavensegat.2"},
    {"label": "Brouwersdam spuisluis binnen schuif6", "value": "brouwersdam.spui.binnen.schuif6"},
    {"label": "Brouwersdam spuisluis buiten schuif2", "value": "brouwersdam.spui.buiten.schuif2"},
    {"label": "Brouwershavensche Gat 08", "value": "brouwershavensche.gat.08"},
    {"label": "Bruinisse Grevelingensluis", "value": "bruinisse.grevelingensluis"},
    {"label": "Bruinisse Krammersluis krammerput", "value": "bruinisse.krammersluis.krammerput"},
    {"label": "Bruinisse Krammersluis laagbekken", "value": "bruinisse.krammersluis.laagbekken"},
    {"label": "Bruinisse Krammersluis Oosterschelde", "value": "bruinisse.krammersluis.oosterschelde.1"},
    {"label": "Bruinisse Krammersluis Oosterschelde", "value": "bruinisse.krammersluis.oosterschelde.2"},
    {"label": "Bruinisse Krammersluis Volkerak Noord", "value": "bruinisse.krammersluis.volkeraknoord"},
    {"label": "Bruinisse Krammersluis Volkerak Zuid", "value": "bruinisse.krammersluis.volkerakzuid"},
    {"label": "Buitenbanken west", "value": "buitenbanken.west"},
    {"label": "Buitenhuizen", "value": "buitenhuizen"},
    {"label": "Bunde, kanaal", "value": "bunde.kanaal"},
    {"label": "Burgum Burgumerdaam boezem", "value": "burgum.burgumerdaam.boezem"},
    {"label": "Cadzand, 1", "value": "cadzand.1"},
    {"label": "Cadzand, 2", "value": "cadzand.2"},
    {"label": "Culemborg", "value": "culemborg"},
    {"label": "D15", "value": "d15"},
    {"label": "Dalem", "value": "dalem"},
    {"label": "Dalfsen, Vechterweerd", "value": "dalfsen.vechterweerd"},
    {"label": "Delden, sluis, beneden", "value": "delden.sluis.beneden"},
    {"label": "Delden, sluis, boven", "value": "delden.sluis.boven"},
    {"label": "Delfzijl Oude Eemskanaal Spuisluis", "value": "delfzijl.oudeeemskanaal.spuisluis"},
    {"label": "Den Helder, De Kooy", "value": "denhelder.dekooy"},
    {"label": "Den Helder, Marsdiep", "value": "denhelder.marsdiep"},
    {"label": "Den Helder Waddenzee Monding Nieuwe Haven", "value": "denhelder.waddenzee.mondingnieuwehaven"},
    {"label": "Den Hoorn Texel Waddenzee Gat van de Stier", "value": "denhoorntexel.waddenzee.gatvandestier"},
    {"label": "Den Oever, IJsselmeer binnenhaven", "value": "denoever.ijsselmeer.binnenhaven"},
    {"label": "Den Oever IJsselmeer Vaargeul", "value": "denoever.ijsselmeer.vaargeul"},
    {"label": "Den Oever, spuisluis, binnen", "value": "denoever.spuisluis.binnen"},
    {"label": "Den Oever, Waddenzee voorhaven", "value": "denoever.waddenzee.voorhaven"},
    {"label": "Den Oever, Waddenzee voorhaven kolk", "value": "denoever.waddenzee.voorhaven.kolk"},
    {"label": "De Steeg", "value": "desteeg"},
    {"label": "Deventer", "value": "deventer"},
    {"label": "Diemen", "value": "diemen"},
    {"label": "Diemen Muiden brug", "value": "diemen.muidenbrug"},
    {"label": "Dinteloord, Volkerak", "value": "dinteloord.volkerak"},
    {"label": "Dishoek", "value": "dishoek"},
    {"label": "Doesburg, IJssel", "value": "doesburg.ijssel"},
    {"label": "Domburger Rassen", "value": "domburgerrassen"},
    {"label": "Dordrecht Dordtsche Kil", "value": "dordrecht.dordtschekil"},
    {"label": "Dordrecht Hollands Diep 000", "value": "dordrecht.hollandschdiep.000"},
    {"label": "Dordrecht Hollands Diep 015", "value": "dordrecht.hollandschdiep.015"},
    {"label": "Dordrecht Hollands Diep 030", "value": "dordrecht.hollandschdiep.030"},
    {"label": "Dordrecht Hollands Diep 045", "value": "dordrecht.hollandschdiep.045"},
    {"label": "Dordrecht Hollands Diep 060", "value": "dordrecht.hollandschdiep.060"},
    {"label": "Dordrecht Hollands Diep 075", "value": "dordrecht.hollandschdiep.075"},
    {"label": "Dordrecht Oude Maas 000", "value": "dordrecht.oudemaas.000"},
    {"label": "Dordrecht Oude Maas 015", "value": "dordrecht.oudemaas.015"},
    {"label": "Dordrecht Oude Maas 030", "value": "dordrecht.oudemaas.030"},
    {"label": "Dordrecht Oude Maas 045", "value": "dordrecht.oudemaas.045"},
    {"label": "Dordrecht Oude Maas 060", "value": "dordrecht.oudemaas.060"},
    {"label": "Dordrecht Oude Maas 075", "value": "dordrecht.oudemaas.075"},
    {"label": "Dordrecht Oude Maas 090", "value": "dordrecht.oudemaas.090"},
    {"label": "Dordrecht Oude Maas 105", "value": "dordrecht.oudemaas.105"},
    {"label": "Dordrecht Oude Maas 120", "value": "dordrecht.oudemaas.120"},
    {"label": "Dordrecht Oude Maas 135", "value": "dordrecht.oudemaas.135"},
    {"label": "Dordrecht Oude Maas 150", "value": "dordrecht.oudemaas.150"},
    {"label": "Dordrecht Oude Maas 165", "value": "dordrecht.oudemaas.165"},
    {"label": "Dordrecht Oude Maas 180", "value": "dordrecht.oudemaas.180"},
    {"label": "Dordrecht Oude Maas 195", "value": "dordrecht.oudemaas.195"},
    {"label": "Dordrecht Oude Maas 210", "value": "dordrecht.oudemaas.210"},
    {"label": "Dordrecht Oude Maas 225", "value": "dordrecht.oudemaas.225"},
    {"label": "Dordrecht Oude Maas 240", "value": "dordrecht.oudemaas.240"},
    {"label": "Dordrecht Oude Maas 255", "value": "dordrecht.oudemaas.255"},
    {"label": "Dordrecht Oude Maas 270", "value": "dordrecht.oudemaas.270"},
    {"label": "Dordrecht Oude Maas 285", "value": "dordrecht.oudemaas.285"},
    {"label": "Dordrecht Oude Maas 300", "value": "dordrecht.oudemaas.300"},
    {"label": "Dordrecht Beneden Merwede", "value": "dordrecht.oudemaas.benedenmerwede"},
    {"label": "Dorkwerd Reitdiep", "value": "dorkwerd.reitdiep"},
    {"label": "Driel, beneden", "value": "driel.beneden"},
    {"label": "Driel, boven", "value": "driel.boven"},
    {"label": "Dronten Reevesluis zuid", "value": "dronten.reevesluis.drontermeer"},
    {"label": "Dronten Reevesluis noord", "value": "dronten.reevesluis.vossemeer"},
    {"label": "Dukegat", "value": "dukegat"},
    {"label": "Echt, kanaal", "value": "echt.kanaal"},
    {"label": "Eefde, gemaal, aflaat 1, schuif 2", "value": "eefde.gemaal.aflaat1.schuif2"},
    {"label": "Eefde, gemaal, aflaat 2", "value": "eefde.gemaal.aflaat2"},
    {"label": "Eefde, gemaal, aflaat 3", "value": "eefde.gemaal.aflaat3"},
    {"label": "Eefde, sluis, beneden", "value": "eefde.sluis.beneden"},
    {"label": "Eefde, sluis, boven", "value": "eefde.sluis.boven"},
    {"label": "Eemdijk", "value": "eemdijk"},
    {"label": "Eemhaven", "value": "eemhaven"},
    {"label": "Eemshaven, Waddenzee", "value": "eemshaven.waddenzee"},
    {"label": "Eibersburen", "value": "eibersburen"},
    {"label": "Eierlandse Gat", "value": "eierlandsegat"},
    {"label": "Eijsden", "value": "eijsden"},
    {"label": "Eijsden, grens", "value": "eijsden.grens"},
    {"label": "Eindhoven Stuw Blaarthem kanaal", "value": "eindhoven.blaarthem.kanaal"},
    {"label": "Eindhoven, Gender", "value": "eindhoven.gender"},
    {"label": "Eisden Mazenhove, Maas", "value": "eisdenmazenhove.maas"},
    {"label": "Eisden Mazenhove, Maesbempder Greend", "value": "eisdenmazenhove.maesbempdergreend"},
    {"label": "Elburg Elburgerbrug", "value": "elburg.elburgerbrug"},
    {"label": "Epen Geul Cottessen", "value": "epen.geul.cottessen"},
    {"label": "Erp, sluis 5, beneden", "value": "erp.sluis5.beneden"},
    {"label": "Erp, sluis 5, boven", "value": "erp.sluis5.boven"},
    {"label": "Erp, Sluis 5, inlaat", "value": "erp.sluis5.inlaat"},
    {"label": "Erp, Sluis 5, uitlaat", "value": "erp.sluis5.uitlaat"},
    {"label": "Eurogeul, DWE", "value": "eurogeul.dwe"},
    {"label": "Eurogeul, E13", "value": "eurogeul.e13"},
    {"label": "Europahaven", "value": "europahaven"},
    {"label": "Europlatform", "value": "europlatform"},
    {"label": "Europlatform 3", "value": "europlatform.3"},
    {"label": "Europoort Calandkanaal west", "value": "europoort.calandkanaal.1"},
    {"label": "Europoort Calandkanaal midden", "value": "europoort.calandkanaal.2"},
    {"label": "Europoort Calandkanaal oost", "value": "europoort.calandkanaal.3"},
    {"label": "Europoort, Harmsenbrug", "value": "europoort.harmsenbrug"},
    {"label": "Europoort, Hartelbrug", "value": "europoort.hartelbrug"},
    {"label": "F16", "value": "f16"},
    {"label": "F3", "value": "f3"},
    {"label": "Friesekust IJsselmeer", "value": "friesekust.ijsselmeer"},
    {"label": "Gat van Borssele", "value": "gatvanborssele"},
    {"label": "Genemuiden", "value": "genemuiden"},
    {"label": "Goeree, lichteiland", "value": "goeree.lichteiland"},
    {"label": "Gouda Hollandsche IJssel", "value": "gouda.hollandscheijssel"},
    {"label": "Goudswaard, Spui", "value": "goudswaard.spui"},
    {"label": "Grave, beneden", "value": "grave.beneden"},
    {"label": "Grave, boven", "value": "grave.boven"},
    {"label": "Griete", "value": "griete"},
    {"label": "Grijpskerk Gaarkeuken oost", "value": "grijpskerk.gaarkeuken.oost"},
    {"label": "Grijpskerk Gaarkeuken west", "value": "grijpskerk.gaarkeuken.west"},
    {"label": "Groningen", "value": "groningen"},
    {"label": "Hagestein, beneden", "value": "hagestein.beneden"},
    {"label": "Hagestein, boven", "value": "hagestein.boven"},
    {"label": "Haghorst, sluis 4, beneden", "value": "haghorst.sluis4.beneden"},
    {"label": "Haghorst, sluis 4, boven", "value": "haghorst.sluis4.boven"},
    {"label": "Haghorst Sluis 4 kolk", "value": "haghorst.sluis4.kolk"},
    {"label": "Haghorst Sluis 4 schuif", "value": "haghorst.sluis4.schuif"},
    {"label": "Haghorst, sluis 4, schuif1", "value": "haghorst.sluis4.schuif1"},
    {"label": "Haghorst, Sluis 4, uitlaat", "value": "haghorst.sluis4.uitlaat"},
    {"label": "Hank, Bergsche Maas", "value": "hank.bergschemaas"},
    {"label": "Hansweert", "value": "hansweert"},
    {"label": "Haringvliet, 1", "value": "haringvliet.1"},
    {"label": "Haringvliet, punt 10", "value": "haringvliet.10"},
    {"label": "Haringvliet, 2", "value": "haringvliet.2"},
    {"label": "Haringvliet, 3", "value": "haringvliet.3"},
    {"label": "Haringvliet, punt 4", "value": "haringvliet.4"},
    {"label": "Harlingen, Waddenzee", "value": "harlingen.waddenzee"},
    {"label": "Hasselt, Zwarte Water", "value": "hasselt.zwartewater"},
    {"label": "Hato Kaya Tilburg", "value": "hato.kayatilburg"},
    {"label": "Hato Marina Kralendijk", "value": "hato.marinakralendijk"},
    {"label": "Hedel", "value": "hedel"},
    {"label": "Heinenoord, Goidschalxoord", "value": "heinenoord.goidschalxoord"},
    {"label": "Hellevoetsluis", "value": "hellevoetsluis"},
    {"label": "Helmond RWZI aflaatwerk", "value": "helmond.aflaat"},
    {"label": "Helmond, aflaat, boven", "value": "helmond.aflaat.boven"},
    {"label": "Helmond, De Vries", "value": "helmond.devries"},
    {"label": "Helmond, Gulden Aa", "value": "helmond.guldenaa"},
    {"label": "Helmond, Gulden Aa, A", "value": "helmond.guldenaa.a"},
    {"label": "Helmond, Gulden Aa, B", "value": "helmond.guldenaa.b"},
    {"label": "Helmond stuw Scheepstal inlaat", "value": "helmond.scheepstal"},
    {"label": "Helmond, Schotense Loop", "value": "helmond.schotenseloop"},
    {"label": "Helmond, sluis, aflaat 1", "value": "helmond.sluis.aflaat1"},
    {"label": "Helmond, sluis, boven", "value": "helmond.sluis.boven"},
    {"label": "Helmond ZuidWillemsvaart Sluis 7", "value": "helmond.sluis7"},
    {"label": "Helmond, Sluis 9, inlaat", "value": "helmond.sluis9.inlaat"},
    {"label": "Helmond, Sluis 9, uitlaat", "value": "helmond.sluis9.uitlaat"},
    {"label": "Helmond, spaarpand", "value": "helmond.spaarpand"},
    {"label": "Helmond, Zuid-Willemsvaart, inlaat Nieuwe Aa", "value": "helmond.zuidwillemsvaart.inlaatnieuweaa"},
    {"label": "Hengelo, Koppelleiding", "value": "hengelo.koppelleiding"},
    {"label": "Hengelo, Oelerbrug", "value": "hengelo.oelerbrug"},
    {"label": "Hengelo, sluis, beneden", "value": "hengelo.sluis.beneden"},
    {"label": "Hengelo, sluis, boven", "value": "hengelo.sluis.boven"},
    {"label": "Herenlaak", "value": "herenlaak"},
    {"label": "Hoek van Holland", "value": "hoekvanholland"},
    {"label": "Hoek van Holland, lage licht", "value": "hoekvanholland.lagelicht"},
    {"label": "Hoek van Holland Maeslantkering", "value": "hoekvanholland.maeslantkering"},
    {"label": "Hoek van Holland, Maeslantkering, Beneden, noord", "value": "hoekvanholland.maeslantkering.beneden.noord"},
    {"label": "Hollandse Kust Noord Alpha", "value": "hollandsekust.noord.alpha"},
    {"label": "Hollandse Kust, Noord Windpark Noord", "value": "hollandsekust.noord.windparknoord"},
    {"label": "Hollandse Kust, Noord Windpark Zuid", "value": "hollandsekust.noord.windparkzuid"},
    {"label": "Hollandse Kust West Alpha", "value": "hollandsekust.west.alpha"},
    {"label": "Hollandse Kust Zuid platform Alpha", "value": "hollandsekust.zuid.alpha"},
    {"label": "Hollandse Kust Zuid platform Alpha 1", "value": "hollandsekust.zuid.alpha.1"},
    {"label": "Hollandse Kust Zuid platform Alpha 2", "value": "hollandsekust.zuid.alpha.2"},
    {"label": "Hollandse Kust, Zuid Windpark Noord", "value": "hollandsekust.zuid.windparknoord"},
    {"label": "Hollandse Kust, Zuid Windpark Zuid", "value": "hollandsekust.zuid.windparkzuid"},
    {"label": "Holtheme Vecht", "value": "holtheme.vecht"},
    {"label": "Holwerd, Veersteiger", "value": "holwerd.veersteiger"},
    {"label": "Houtribdijk, IJsselmeer", "value": "houtribdijk.ijsselmeer"},
    {"label": "Huibertgat", "value": "huibertgat"},
    {"label": "Huissen, Nederrijn", "value": "huissen.nederrijn"},
    {"label": "IJGeul, 1", "value": "ijgeul.1"},
    {"label": "IJgeul, 2", "value": "ijgeul.2"},
    {"label": "IJgeul, 3", "value": "ijgeul.3"},
    {"label": "IJmuiden, buitenhaven", "value": "ijmuiden.buitenhaven"},
    {"label": "IJmuiden, havenhoofd, zuid", "value": "ijmuiden.havenhoofd.zuid"},
    {"label": "IJmuiden, munitiestort, 1", "value": "ijmuiden.munitiestort.1"},
    {"label": "IJmuiden Munitiestort 2", "value": "ijmuiden.munitiestort.2"},
    {"label": "IJmuiden, noordersluis, oost", "value": "ijmuiden.noordersluis.oost"},
    {"label": "IJmuiden, noordersluis, west", "value": "ijmuiden.noordersluis.west"},
    {"label": "J6", "value": "j6"},
    {"label": "K13a", "value": "k13a"},
    {"label": "K13a", "value": "k13a.1"},
    {"label": "K14", "value": "k14"},
    {"label": "Kadoelen, Zwanediep", "value": "kadoelen.zwanediep"},
    {"label": "Kampen, IJssel", "value": "kampen.ijssel"},
    {"label": "Kampen, Keteldiep", "value": "kampen.keteldiep"},
    {"label": "Kampen Scheeresluis beneden", "value": "kampen.scheeresluis.beneden"},
    {"label": "Kamperland, Schotsman", "value": "kamperland.schotsman"},
    {"label": "Kanne", "value": "kanne"},
    {"label": "Kats Zanskreekdam", "value": "kats.zandkreekdam"},
    {"label": "Kats, Zandkreeksluis", "value": "kats.zandkreeksluis"},
    {"label": "Kats Zandkreeksluis buiten", "value": "kats.zandkreeksluis.buiten"},
    {"label": "Kast Zanskreeksluis kolk1", "value": "kats.zandkreeksluis.kolk1"},
    {"label": "Ketelhaven, Ketelmeer", "value": "ketelhaven.ketelmeer"},
    {"label": "Kinderdijk Lek", "value": "kinderdijk.lek"},
    {"label": "Kloosterzande, Baalhoek", "value": "kloosterzande.baalhoek"},
    {"label": "Knock", "value": "knock"},
    {"label": "Kornwerderzand, IJsselmeer binnenhaven", "value": "kornwerderzand.ijsselmeer.binnenhaven"},
    {"label": "Kornwerderzand IJsselmeer Middelgronden", "value": "kornwerderzand.ijsselmeer.middelgronden"},
    {"label": "Kornwerderzand IJsselmeer spui", "value": "kornwerderzand.ijsselmeer.spui"},
    {"label": "Kornwerderzand IJsselmeer vaargeul", "value": "kornwerderzand.ijsselmeer.vaargeul"},
    {"label": "Kornwerderzand, Waddenzee voorhaven kolk", "value": "kornwerderzand.waddenzee.voorhaven.kolk"},
    {"label": "Krabbersgat, IJsselmeer", "value": "krabbersgat.ijsselmeer"},
    {"label": "Kralendijk Plazabeach Terminal", "value": "kralendijk.plazabeachterminal"},
    {"label": "Krammersluizen west", "value": "krammersluizen.west"},
    {"label": "Krimpen aan de IJssel, Hollandsche IJssel", "value": "krimpenaandeijssel.hollandscheijssel"},
    {"label": "Krimpen aan de Lek, Lek", "value": "krimpenaandelek.lek"},
    {"label": "L9", "value": "l9"},
    {"label": "Lanaken", "value": "lanaken"},
    {"label": "Lauwersoog, Waddenzee", "value": "lauwersoog.waddenzee"},
    {"label": "Leeuwarden Van Harinxmakanaal", "value": "leeuwarden.vanharinxmakanaal"},
    {"label": "Lelystad, Houtribsluis, zuid", "value": "lelystad.houtribsluis.zuid"},
    {"label": "Lemmer Ijsselmeer Woudagemaal", "value": "lemmer.ijsselmeer.woudagemaal"},
    {"label": "Lemmer stroomkanaal Teroelsterkolk", "value": "lemmer.stroomkanaal.teroelsterkolk"},
    {"label": "Lemmer Teroelsterkolk buiten", "value": "lemmer.teroelsterkolk.buiten"},
    {"label": "Lemmer stroomkanaal Woudagemaal", "value": "lemmer.woudagemaal.stroomkanaal"},
    {"label": "Lierop, sluis 10, beneden", "value": "lierop.sluis10.beneden"},
    {"label": "Lierop, sluis 10, boven", "value": "lierop.sluis10.boven"},
    {"label": "Lierop ZuidWillemsvaart Sluis 9", "value": "lierop.sluis9"},
    {"label": "Lierop ZuidWillemsvaart Sluis 9 boven", "value": "lierop.sluis9.boven"},
    {"label": "Lieshout, Donkersvoortseloop", "value": "lieshout.donkersvoortseloop"},
    {"label": "Linne, stuw, boven", "value": "linne.stuw.boven"},
    {"label": "Lith, beneden dorp", "value": "lith.beneden"},
    {"label": "Lith, boven", "value": "lith.boven"},
    {"label": "Lith, beneden sluis", "value": "lith.sluis"},
    {"label": "Lixhe Bief Aval", "value": "lixhebiefaval"},
    {"label": "Lobith, Bovenrijn, haven", "value": "lobith.bovenrijn.haven"},
    {"label": "Lobith, Bovenrijn, Tolkamer", "value": "lobith.bovenrijn.tolkamer"},
    {"label": "Maarssen, kanaal", "value": "maarssen.kanaal"},
    {"label": "Maaseik", "value": "maaseik"},
    {"label": "Maasgeul 2", "value": "maasgeul.2"},
    {"label": "Maassluis", "value": "maassluis"},
    {"label": "Maastricht, Borgharen, Julianakanaal", "value": "maastricht.borgharen.julianakanaal"},
    {"label": "Maastricht, Borgharen, Maas, beneden", "value": "maastricht.borgharen.maas.beneden"},
    {"label": "Maastricht, Borgharen, Maas, boven", "value": "maastricht.borgharen.maas.boven"},
    {"label": "Maastricht Bosscherveld overlaat", "value": "maastricht.bosscherveld"},
    {"label": "Maastricht, Sint Pieter", "value": "maastricht.sintpieter"},
    {"label": "Maastricht Sint Pieter zuid", "value": "maastricht.sintpieter.zuid"},
    {"label": "Maasvlakte Amaliahaven", "value": "maasvlakte.amaliahaven"},
    {"label": "Maasvlakte Beergat", "value": "maasvlakte.beergat"},
    {"label": "Maasvlakte Europahaven", "value": "maasvlakte.europahaven"},
    {"label": "Maasvlakte, Hartelhaven", "value": "maasvlakte.hartelhaven"},
    {"label": "Maasvlakte Papegaaiebek", "value": "maasvlakte.papegaaiebek"},
    {"label": "Maasvlakte Slufter", "value": "maasvlakte.slufter"},
    {"label": "Makkum sluis buiten", "value": "makkum.sluis.buiten"},
    {"label": "Malden Maaswaalkanaal Inlaat Teersesluispolder", "value": "malden.maaswaalkanaal.inlaatteersesluispolder"},
    {"label": "Markelo", "value": "markelo"},
    {"label": "Markermeer, midden", "value": "markermeer.midden"},
    {"label": "Markermeer Trintelzand", "value": "markermeer.trintelzand"},
    {"label": "Marknesse", "value": "marknesse"},
    {"label": "Marollegat", "value": "marollegat"},
    {"label": "Maurik Mauriksewetering", "value": "maurik.mauriksewetering"},
    {"label": "Megen, Maas", "value": "megen.maas"},
    {"label": "Meijel Stuw Katsberg beneden", "value": "meijel.kanaal.beneden"},
    {"label": "Meijel Stuw Katsberg boven", "value": "meijel.kanaal.boven"},
    {"label": "Meppel, hoofdvaart", "value": "meppel.hoofdvaart"},
    {"label": "Middelharnis, meetboei", "value": "middelharnis.meetboei"},
    {"label": "Mierlo, Goorloop, gemaal", "value": "mierlo.goorloop.gemaal"},
    {"label": "Mierlo Goorloop inlaat1", "value": "mierlo.goorloop.inlaat1"},
    {"label": "Millingen a/d Rijn", "value": "millingenaanderijn"},
    {"label": "Moerdijk", "value": "moerdijk"},
    {"label": "Mook", "value": "mook"},
    {"label": "Nederweert, sluis 15, boven", "value": "nederweert.sluis15.boven"},
    {"label": "Nederweert, Sluis 15, bypass", "value": "nederweert.sluis15.bypass"},
    {"label": "Nederweert, Sluis 15, inlaat", "value": "nederweert.sluis15.inlaat"},
    {"label": "Nederweert, Sluis 15, uitlaat", "value": "nederweert.sluis15.uitlaat"},
    {"label": "Nederweert, sluis 15, voedingskanaal", "value": "nederweert.sluis15.voedingskanaal"},
    {"label": "Nederweert, Sluis 15, voedingskanaal 1", "value": "nederweert.sluis15.voedingskanaal1"},
    {"label": "Nederweert, Sluis 15, voedingskanaal 2", "value": "nederweert.sluis15.voedingskanaal2"},
    {"label": "Nederweert-Eind", "value": "nederweerteind.noordervaart"},
    {"label": "Negenoord, oost", "value": "negenoord.oost"},
    {"label": "Negenoord, west", "value": "negenoord.west"},
    {"label": "Nieuw Beerta", "value": "nieuwbeerta"},
    {"label": "Nieuwegein, Doorslag", "value": "nieuwegein.doorslag"},
    {"label": "Nieuwegein, lekkanaal", "value": "nieuwegein.lekkanaal"},
    {"label": "Nieuwe Statenzijl, Dollard", "value": "nieuwestatenzijl.dollard"},
    {"label": "Nieuwnamen Overloop van Valkenisse", "value": "nieuwnamen.overloopvanvalkenisse"},
    {"label": "Nieuw-Vossemeer", "value": "nieuwvossemeer"},
    {"label": "Nijkerk, Nijkerkernauw", "value": "nijkerk.nijkerkernauw"},
    {"label": "Nijkerk, Nuldernauw", "value": "nijkerk.nuldernauw"},
    {"label": "Nijmegen Maaswaalkanaal Inlaat Landsweijer", "value": "nijmegen.maaswaalkanaal.inlaatlandsweijer"},
    {"label": "Nijmegen, Waal", "value": "nijmegen.waal"},
    {"label": "Olst", "value": "olst"},
    {"label": "Ommen, Ommerkanaal", "value": "ommen.ommerkanaal"},
    {"label": "Ommen, Vecht", "value": "ommen.vecht"},
    {"label": "Oosterhout, Marksluis, beneden", "value": "oosterhout.marksluis.beneden"},
    {"label": "Oosterhout, Marksluis, boven", "value": "oosterhout.marksluis.boven"},
    {"label": "Oosterhout, Marksluis, inlaat", "value": "oosterhout.marksluis.inlaat"},
    {"label": "Oosterhout, Marksluis, uitlaat", "value": "oosterhout.marksluis.uitlaat"},
    {"label": "Oosterhout, sluis 1, boven", "value": "oosterhout.sluis1.boven"},
    {"label": "Oosterhout, Sluis 1, gemaal", "value": "oosterhout.sluis1.gemaal"},
    {"label": "Oosterhout, Sluis 1, inlaat", "value": "oosterhout.sluis1.inlaat"},
    {"label": "Oosterhout, Sluis 1, kolk", "value": "oosterhout.sluis1.kolk"},
    {"label": "Oosterhout, Sluis 1, spui", "value": "oosterhout.sluis1.spui"},
    {"label": "Oosterhout, sluis 1, spuikanaal", "value": "oosterhout.sluis1.spuikanaal"},
    {"label": "Oosterhout, Sluis 1, spuikanaal, klep rechts", "value": "oosterhout.sluis1.spuikanaal.kleprechts"},
    {"label": "Oosterhout, Sluis 1, uitlaat", "value": "oosterhout.sluis1.uitlaat"},
    {"label": "Oosterschelde, 11", "value": "oosterschelde.11"},
    {"label": "Oosterschelde, 14", "value": "oosterschelde.14"},
    {"label": "Oosterschelde, 4", "value": "oosterschelde.4"},
    {"label": "Oosterschelde Roompotsluis binnen", "value": "oosterschelde.roompotsluis.binnen"},
    {"label": "Oosterschelde Roompotsluis buiten", "value": "oosterschelde.roompotsluis.buiten"},
    {"label": "Ossenisse", "value": "ossenisse"},
    {"label": "Oude Westereems noord boei 1", "value": "oude.westereems.noord.boei.1"},
    {"label": "Oude Westereems, zuid", "value": "oudewestereems.zuid"},
    {"label": "P11", "value": "p11"},
    {"label": "Panheel, gemaal", "value": "panheel.gemaal"},
    {"label": "Panheel, sluis, boven", "value": "panheel.sluis.boven"},
    {"label": "Panheel, sluis, inlaat", "value": "panheel.sluis.inlaat"},
    {"label": "Panheel, sluis, uitlaat", "value": "panheel.sluis.uitlaat"},
    {"label": "Pannerden, Pannerdensch kanaal", "value": "pannerden.pannerdenschkanaal"},
    {"label": "Pannerden, regelwerk, beneden", "value": "pannerden.regelwerk.beneden"},
    {"label": "Pannerden, regelwerk, boven", "value": "pannerden.regelwerk.boven"},
    {"label": "Parksluis", "value": "parksluis"},
    {"label": "Plaat van Oude Tonge, oost", "value": "plaatvanoudetonge.oost"},
    {"label": "Poeldonk, Aa, uitlaat", "value": "poeldonk.aa.uitlaat"},
    {"label": "Pogum", "value": "pogum"},
    {"label": "Q1 platform", "value": "q1.1"},
    {"label": "Ramspolkering Ketelmeerzijde", "value": "ramspolkering.ketelmeer"},
    {"label": "Rhenen Grebbeberg", "value": "rhenen.grebbeberg"},
    {"label": "Rijswijk Drielandenpunt", "value": "rijswijk.drielandenpunt"},
    {"label": "Rilland, Antwerps kanaalpand", "value": "rilland.antwerpskanaalpand"},
    {"label": "Rilland, Bath", "value": "rilland.bath"},
    {"label": "Rilland, Bathsebrug", "value": "rilland.bathsebrug"},
    {"label": "Rilland, Bathse Spuikanaal, inloop", "value": "rilland.bathsespuikanaal.inloop"},
    {"label": "Rilland Bathse spuisluis", "value": "rilland.bathsespuisluis"},
    {"label": "Rilland Bathse spuisluis binnen", "value": "rilland.bathsespuisluis.binnen"},
    {"label": "Rilland Bathse spuisluis buiten", "value": "rilland.bathsespuisluis.buiten"},
    {"label": "Roermond, Hambeek", "value": "roermond.hambeek"},
    {"label": "Roermond, stuw, boven", "value": "roermond.stuw.boven"},
    {"label": "Roggenplaat", "value": "roggenplaat"},
    {"label": "Rosmalen, Hintham, beneden", "value": "rosmalen.hintham.beneden"},
    {"label": "Rosmalen Hinthamsluis beneden", "value": "rosmalen.hinthamsluis.beneden"},
    {"label": "Rosmalen Hinthamsluis boven", "value": "rosmalen.hinthamsluis.boven"},
    {"label": "Rotem", "value": "rotem"},
    {"label": "Rotterdam, Brienenoordbrug", "value": "rotterdam.brienenoordbrug"},
    {"label": "Rotterdam IJzerwerkerkade", "value": "rotterdam.ijzerwerkerkade"},
    {"label": "Rotterdam, Lekhaven", "value": "rotterdam.lekhaven"},
    {"label": "Rotterdam, luchthaven", "value": "rotterdam.luchthaven"},
    {"label": "Rotterdam Waalhaven 1", "value": "rotterdam.waalhaven.1"},
    {"label": "Rotterdamsehoek IJsselmeer", "value": "rotterdamsehoek.ijsselmeer"},
    {"label": "Rozenburg Het Scheur", "value": "rozenburg.hetscheur"},
    {"label": "Rozenburgsesluis, noordzijde", "value": "rozenburgsesluis.noordzijde"},
    {"label": "Rozenburgsesluis, zuidzijde", "value": "rozenburgsesluis.zuidzijde"},
    {"label": "Sambeek, beneden", "value": "sambeek.beneden"},
    {"label": "Sambeek, boven", "value": "sambeek.boven"},
    {"label": "Sas van Gent", "value": "sasvangent"},
    {"label": "Schaar Stroomgat", "value": "schaar.stroomgat"},
    {"label": "Schaar van de Noord", "value": "schaarvandenoord"},
    {"label": "Schiermonnikoog, noord", "value": "schiermonnikoog.noord"},
    {"label": "Schiermonnikoog, Waddenzee", "value": "schiermonnikoog.waddenzee"},
    {"label": "Schiermonnikoog, Westgat", "value": "schiermonnikoog.westgat"},
    {"label": "Schijndel", "value": "schijndel"},
    {"label": "Schijndel, sluis, beneden", "value": "schijndel.sluis.beneden"},
    {"label": "Schijndel, sluis, boven", "value": "schijndel.sluis.boven"},
    {"label": "Schijndel, sluis, inlaat", "value": "schijndel.sluis.inlaat"},
    {"label": "Schijndel sluis kolk", "value": "schijndel.sluis.kolk"},
    {"label": "Schijndel, sluis, spuikanaal", "value": "schijndel.sluis.spuikanaal"},
    {"label": "Schoonhoven", "value": "schoonhoven"},
    {"label": "Schouwenbank, 1", "value": "schouwenbank.1"},
    {"label": "Schouwenbank, 2", "value": "schouwenbank.2"},
    {"label": "'s-Hertogenbosch Crevecoeur", "value": "shertogenbosch.crevecoeur"},
    {"label": "Empel, kanaal", "value": "shertogenbosch.empel.kanaal"},
    {"label": "Empel, Maas", "value": "shertogenbosch.empel.maas"},
    {"label": "'s-Hertogenbosch Engelen", "value": "shertogenbosch.engelen"},
    {"label": "'s-Hertogenbosch Engelen Dieze", "value": "shertogenbosch.engelen.dieze"},
    {"label": "'s-Hertogenbosch, Poeldonk, aa", "value": "shertogenbosch.poeldonk.aa"},
    {"label": "'s-Hertogenbosch, Poeldonk, Zuid-Willemsvaart", "value": "shertogenbosch.poeldonk.zuidwillemsvaart"},
    {"label": "Sint Annaland, Haven Steiger", "value": "sintannaland.havensteiger"},
    {"label": "Sint Annaland haven", "value": "sintannaland.oosterschelde"},
    {"label": "Sint Philipsland Slaak noord", "value": "sintphilipsland.slaak.noord"},
    {"label": "Sint Philipsland Slaak oost", "value": "sintphilipsland.slaak.oost"},
    {"label": "Sint Philipsland Slaak zuid", "value": "sintphilipsland.slaak.zuid"},
    {"label": "Slochtersluis", "value": "slochtersluis.boven"},
    {"label": "Smeermaas, Zuid-Willemsvaart", "value": "smeermaas.zuidwillemsvaart"},
    {"label": "Someren, sluis 11, beneden", "value": "someren.sluis11.beneden"},
    {"label": "Someren, sluis 11, boven", "value": "someren.sluis11.boven"},
    {"label": "Someren, sluis 12, beneden", "value": "someren.sluis12.beneden"},
    {"label": "Someren, sluis 12, boven", "value": "someren.sluis12.boven"},
    {"label": "Someren, sluis 13", "value": "someren.sluis13"},
    {"label": "Someren, sluis 13, beneden", "value": "someren.sluis13.beneden"},
    {"label": "Someren, sluis 13, boven", "value": "someren.sluis13.boven"},
    {"label": "Son en Breugel inlaat Beekse Waterloop", "value": "sonenbreugel.beeksewaterloop"},
    {"label": "Son en Breugel inlaat Wilhelminakanaal", "value": "sonenbreugel.wilhelminakanaal"},
    {"label": "Spaanjerd", "value": "spaanjerd"},
    {"label": "Spaarndam, Zijkanaal C", "value": "spaarndam.zijkanaalc"},
    {"label": "Spijkenisse, Beerenplaat", "value": "spijkenisse.beerenplaat"},
    {"label": "Spijkenisse, Oude Maas", "value": "spijkenisse.oudemaas"},
    {"label": "Spijkenisse, Oude Maas, Brug", "value": "spijkenisse.oudemaas.brug"},
    {"label": "Stavenisse", "value": "stavenisse"},
    {"label": "Stavenisse, keeten", "value": "stavenisse.keeten"},
    {"label": "Stavoren gemaal Hoogland buiten", "value": "stavoren.gemaalhoogland.buiten"},
    {"label": "Stavoren IJsselmeer", "value": "stavoren.ijsselmeer"},
    {"label": "Stavoren JohanFrisokanaal gemaal Hoogland inlaat", "value": "stavoren.johanfrisokanaal"},
    {"label": "Stellendam, binnen", "value": "stellendam.binnen"},
    {"label": "Stellendam, buiten", "value": "stellendam.buiten"},
    {"label": "Stellendam, buitenhaven", "value": "stellendam.buitenhaven"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 1", "value": "stellendam.haringvlietsluizen.schuif1"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 11", "value": "stellendam.haringvlietsluizen.schuif11"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 13", "value": "stellendam.haringvlietsluizen.schuif13"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 14", "value": "stellendam.haringvlietsluizen.schuif14"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 15", "value": "stellendam.haringvlietsluizen.schuif15"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 16", "value": "stellendam.haringvlietsluizen.schuif16"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 3", "value": "stellendam.haringvlietsluizen.schuif3"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 4", "value": "stellendam.haringvlietsluizen.schuif4"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 5", "value": "stellendam.haringvlietsluizen.schuif5"},
    {"label": "Stellendam, Haringvlietsluizen, schuif 8", "value": "stellendam.haringvlietsluizen.schuif8"},
    {"label": "Stevensweert", "value": "stevensweert"},
    {"label": "Steyl", "value": "steyl"},
    {"label": "Stortemelk, oost", "value": "stortemelk.oost"},
    {"label": "Suurhofbrug, noordzijde", "value": "suurhofbrug.noordzijde"},
    {"label": "Tennesseehaven", "value": "tennesseehaven"},
    {"label": "Terherne beneden", "value": "terherne.beneden"},
    {"label": "Terherne boven", "value": "terherne.boven"},
    {"label": "Terneuzen", "value": "terneuzen"},
    {"label": "Terneuzen Pas van Terneuzen boei", "value": "terneuzen.pasvanterneuzen.1"},
    {"label": "Terneuzen, Sluiskilbrug", "value": "terneuzen.sluiskilbrug"},
    {"label": "Terneuzen, westsluis", "value": "terneuzen.westsluis"},
    {"label": "Terneuzen, westsluis, buiten", "value": "terneuzen.westsluis.buiten"},
    {"label": "Terschelling, Hoorn", "value": "terschelling.hoorn"},
    {"label": "Terschelling, Noordzee", "value": "terschelling.noordzee"},
    {"label": "Terschelling, west", "value": "terschelling.west"},
    {"label": "Texelhors", "value": "texel.hors"},
    {"label": "Texel, Oudeschild", "value": "texel.oudeschild"},
    {"label": "Tholen Bergsediepsluis", "value": "tholen.bergsediepsluis"},
    {"label": "Tholen, Bergse Diepsluis, buiten", "value": "tholen.bergsediepsluis.buiten"},
    {"label": "Tiel, kanaal", "value": "tiel.kanaal"},
    {"label": "Tiel, Waal", "value": "tiel.waal"},
    {"label": "Tilburg, sluis 2, beneden", "value": "tilburg.sluis2.beneden"},
    {"label": "Tilburg, sluis 2, boven", "value": "tilburg.sluis2.boven"},
    {"label": "Tilburg Sluis 3", "value": "tilburg.sluis3"},
    {"label": "Tilburg, sluis 3, beneden", "value": "tilburg.sluis3.beneden"},
    {"label": "Tilburg, sluis 3, boven", "value": "tilburg.sluis3.boven"},
    {"label": "Tilburg Sluis 3 kolk", "value": "tilburg.sluis3.kolk"},
    {"label": "Uikhoven", "value": "uikhoven"},
    {"label": "Uithuizerwad", "value": "uithuizerwad"},
    {"label": "Veessen Wapenveld", "value": "veessen"},
    {"label": "Veghel, sluis 4, beneden", "value": "veghel.sluis4.beneden"},
    {"label": "Veghel, sluis 4, boven", "value": "veghel.sluis4.boven"},
    {"label": "Veghel, Sluis 4, inlaat", "value": "veghel.sluis4.inlaat"},
    {"label": "Veghel, Sluis 4, uitlaat", "value": "veghel.sluis4.uitlaat"},
    {"label": "Velserkom", "value": "velsen.velserkom"},
    {"label": "Velsen-Zuid, Spaarndammerpolder", "value": "velsenzuid.spaarndammerpolder"},
    {"label": "Venlo", "value": "venlo"},
    {"label": "Vlaardingen", "value": "vlaardingen"},
    {"label": "Vlakte van de Raan", "value": "vlaktevanderaan"},
    {"label": "Vlakte van de Raan Deurloo", "value": "vlaktevanderaan.deurloo"},
    {"label": "Vlieland, haven", "value": "vlieland.haven"},
    {"label": "Vlieland, west", "value": "vlieland.west"},
    {"label": "Vlissingen", "value": "vlissingen"},
    {"label": "Vlissingen Honte", "value": "vlissingen.honte"},
    {"label": "Waalwijk", "value": "waalwijk"},
    {"label": "Walsoorden", "value": "walsoorden"},
    {"label": "Weert, Lozen", "value": "weert.lozen"},
    {"label": "Weert, sluis 16, beneden", "value": "weert.sluis16.beneden"},
    {"label": "Weert, sluis 16, boven", "value": "weert.sluis16.boven"},
    {"label": "Weesp, Amsterdam-Rijnkanaal", "value": "weesp.amsterdamrijnkanaal"},
    {"label": "Well", "value": "well"},
    {"label": "Werkendam, Binnen Kievitswaard", "value": "werkendam.binnenkievitswaard"},
    {"label": "Werkendam, Happen Hennip", "value": "werkendam.happenhennip"},
    {"label": "Werkendam, Nieuwe Merwede", "value": "werkendam.nieuwemerwede"},
    {"label": "Werkendam, Steurgat", "value": "werkendam.steurgat"},
    {"label": "Werkendam, Vogelenzang", "value": "werkendam.vogelenzang"},
    {"label": "Westereems, west", "value": "westereems.west"},
    {"label": "Westervoort", "value": "westervoort"},
    {"label": "Westervoort, 1", "value": "westervoort.1"},
    {"label": "Westervoort, 2", "value": "westervoort.2"},
    {"label": "Westervoort Hondsbroeksche Pleij IJssel", "value": "westervoort.hondbroekschepleij.ijssel"},
    {"label": "Westervoort IJsselkop", "value": "westervoort.ijsselkop"},
    {"label": "Westkapelle", "value": "westkapelle"},
    {"label": "Wielingen, noord", "value": "wielingen.noord"},
    {"label": "Wieringen IJsselmeer oost", "value": "wieringen.ijsselmeer.oost"},
    {"label": "Wierumergronden", "value": "wierumergronden"},
    {"label": "Wijdenes", "value": "wijdenes"},
    {"label": "Wijhe", "value": "wijhe"},
    {"label": "Wijk bij Duurstede, Amsterdam-Rijnkanaal", "value": "wijkbijduurstede.amsterdamrijnkanaal"},
    {"label": "Wilhelminadorp", "value": "wilhelminadorp"},
    {"label": "Willemstad, Hollandsch Diep", "value": "willemstad.hollandschdiep"},
    {"label": "Willemstad Hollandschdiep Volkerakspuisluis", "value": "willemstad.hollandschdiep.volkerakspuisluis"},
    {"label": "Willemstad Volkeraksluizen gat2", "value": "willemstad.volkeraksluizen.schuif2"},
    {"label": "Willemstad Volkeraksluizen gat3", "value": "willemstad.volkeraksluizen.schuif3"},
    {"label": "Zaltbommel", "value": "zaltbommel"},
    {"label": "Zierikzee Zeelandbrug", "value": "zierikzee.zeelandbrug"},
    {"label": "Zoelen Beuningengemaal", "value": "zoelen.beuningengemaal"},
    {"label": "Zuidland, Spui", "value": "zuidland.spui"},
    {"label": "Zutphen, IJssel", "value": "zutphen.ijssel"},
    {"label": "Zwartsluis gemaal pomp1", "value": "zwartsluis.gemaal.pomp1"},
    {"label": "Zwartsluis, Meppelerdiep", "value": "zwartsluis.meppelerdiep"},
    {"label": "Zwartsluis, Zwarte Water", "value": "zwartsluis.zwartewater"},
    {"label": "Zwolle, IJssel", "value": "zwolle.ijssel"},
    {"label": "Zwolle, Zwarte Water, kanaal", "value": "zwolle.zwartewater.kanaal"},
]