"""Locations for the RWS waterinfo integration."""
"""Generated 27-09-2025 09:30:31."""
"""Active only: True."""
"""With code: True."""

CONF_LOC_OPTIONS = [
    {"label": "A12 platform (A12)", "value": "A12"},
    {"label": "Schijndelse loop (AA03)", "value": "AA03"},
    {"label": "Almen (ALME)", "value": "ALME"},
    {"label": "Amaliahaven (AMHV)", "value": "AMHV"},
    {"label": "Amerongen boven (AMRB)", "value": "AMRB"},
    {"label": "Amerongen beneden (AMRO)", "value": "AMRO"},
    {"label": "Antwerps kanaalpand (ANKA)", "value": "ANKA"},
    {"label": "Antwerps kanaalpand (b) (ANKAb)", "value": "ANKAb"},
    {"label": "Antwerps kanaalpand (o) (ANKAo)", "value": "ANKAo"},
    {"label": "Arnhem (ARNH)", "value": "ARNH"},
    {"label": "AWG platform (AWG)", "value": "AWG"},
    {"label": "Baalhoek (b) (BAALb)", "value": "BAALb"},
    {"label": "Baalhoek (o) (BAALo)", "value": "BAALo"},
    {"label": "Bath (BATH)", "value": "BATH"},
    {"label": "Bathse brug Deltanuts (b) (BBDTb)", "value": "BBDTb"},
    {"label": "Bathse brug Deltanuts (o) (BBDTo)", "value": "BBDTo"},
    {"label": "Bergsediepsluis (BDSL)", "value": "BDSL"},
    {"label": "Bergsediepsluis wind (BDWI)", "value": "BDWI"},
    {"label": "Bernisse NAP -3m (BER30)", "value": "BER30"},
    {"label": "Berkhout (BERK)", "value": "BERK"},
    {"label": "Bernisse Zuidland (BERN)", "value": "BERN"},
    {"label": "Brouwershavense Gat 2 (BG2)", "value": "BG2"},
    {"label": "Brouwershavense Gat 2 (b) (BG2b)", "value": "BG2b"},
    {"label": "Brouwershavense Gat 2 (o) (BG2o)", "value": "BG2o"},
    {"label": "Brouwershavense Gat 8 (b) (BG8b)", "value": "BG8b"},
    {"label": "Brouwershavense Gat 8 (o) (BG8o)", "value": "BG8o"},
    {"label": "Berghaven H v Holland (BGH1)", "value": "BGH1"},
    {"label": "Borgharen Julianakanaal 2 (BHJE)", "value": "BHJE"},
    {"label": "Binnen Kievitswaard (BKWD)", "value": "BKWD"},
    {"label": "Blaarthem boven (BLAB)", "value": "BLAB"},
    {"label": "Beuningengemaal (BNGG)", "value": "BNGG"},
    {"label": "Bommenede 1 (b) (BOM1b)", "value": "BOM1b"},
    {"label": "Bommenede 1 (o) (BOM1o)", "value": "BOM1o"},
    {"label": "Borgharen Dorp (BORD)", "value": "BORD"},
    {"label": "Borssele (BORS)", "value": "BORS"},
    {"label": "Brienenoordbrug NAP-6.5 m (BRB65)", "value": "BRB65"},
    {"label": "Burgumerdaam Boezem (BRGD)", "value": "BRGD"},
    {"label": "Stuw Borgsweer (BRGW)", "value": "BRGW"},
    {"label": "Brouwersdam 2 buiten Zuid (BRO2)", "value": "BRO2"},
    {"label": "Brouwersdam 6 binnen Zuid (BRO6)", "value": "BRO6"},
    {"label": "Borssele Alpha (BSA)", "value": "BSA"},
    {"label": "Benedensas Sluis (BSASS)", "value": "BSASS"},
    {"label": "Bathse spuisluis D (BSBSD)", "value": "BSBSD"},
    {"label": "Bathse spuisluis Ws (BSBSW)", "value": "BSBSW"},
    {"label": "Bathse spuisluis kanaal (BSBSZ)", "value": "BSBSZ"},
    {"label": "Buitenbanken west (BUBW)", "value": "BUBW"},
    {"label": "Bunde (BUND)", "value": "BUND"},
    {"label": "Cadzand boei (CADW)", "value": "CADW"},
    {"label": "Cadzand wind (CAWI)", "value": "CAWI"},
    {"label": "Crevecoeur (CREV)", "value": "CREV"},
    {"label": "Crevecoeur boven (CREVB)", "value": "CREVB"},
    {"label": "D15 platform (D15)", "value": "D15"},
    {"label": "Delden boven (DELB)", "value": "DELB"},
    {"label": "Delden beneden (DELO)", "value": "DELO"},
    {"label": "Deurloo (DEUR)", "value": "DEUR"},
    {"label": "Deventer (DEVE)", "value": "DEVE"},
    {"label": "Diemen (NAP -1.4m) (DIE14)", "value": "DIE14"},
    {"label": "Diemen (NAP -6.5m) (DIE65)", "value": "DIE65"},
    {"label": "Delfzijl (DLFZ)", "value": "DLFZ"},
    {"label": "Drielandenpunt (DLPT)", "value": "DLPT"},
    {"label": "Inlaat Son en Breugel (DM13)", "value": "DM13"},
    {"label": "Inlaat Beekse Waterloop (DM14)", "value": "DM14"},
    {"label": "Dodewaard (DODE)", "value": "DODE"},
    {"label": "Doesburg brug (DOES)", "value": "DOES"},
    {"label": "Doorslag (DOOR)", "value": "DOOR"},
    {"label": "Domburger Rassen (DORA)", "value": "DORA"},
    {"label": "Dordrecht (DORD)", "value": "DORD"},
    {"label": "Dorkwerd (DORK)", "value": "DORK"},
    {"label": "Driel boven (DRIB)", "value": "DRIB"},
    {"label": "Driel beneden (DRIO)", "value": "DRIO"},
    {"label": "Dintelsas (DSAS)", "value": "DSAS"},
    {"label": "Duivelseiland 015 (DU015)", "value": "DU015"},
    {"label": "Duivelseiland 030 (DU030)", "value": "DU030"},
    {"label": "Duivelseiland 045 (DU045)", "value": "DU045"},
    {"label": "Duivelseiland 060 (DU060)", "value": "DU060"},
    {"label": "Duivelseiland 090 (DU090)", "value": "DU090"},
    {"label": "Duivelseiland  105 (DU105)", "value": "DU105"},
    {"label": "Duivelseiland  120 (DU120)", "value": "DU120"},
    {"label": "Duivelseiland  135 (DU135)", "value": "DU135"},
    {"label": "Duivelseiland  150 (DU150)", "value": "DU150"},
    {"label": "Duivelseiland  165 (DU165)", "value": "DU165"},
    {"label": "Duivelseiland  180 (DU180)", "value": "DU180"},
    {"label": "Duivelseiland  195 (DU195)", "value": "DU195"},
    {"label": "Duivelseiland  225 (DU225)", "value": "DU225"},
    {"label": "Duivelseiland  255 (DU255)", "value": "DU255"},
    {"label": "Duivelseiland  285 (DU285)", "value": "DU285"},
    {"label": "Eurogeul DWE (DWE1)", "value": "DWE1"},
    {"label": "Eurogeul E13 (E13)", "value": "E13"},
    {"label": "Echt (ECHT)", "value": "ECHT"},
    {"label": "Eefde boven (EEFB)", "value": "EEFB"},
    {"label": "Eefde beneden (EEFO)", "value": "EEFO"},
    {"label": "Eemdijk (EEMDK)", "value": "EEMDK"},
    {"label": "Eijsden grens (EIJS)", "value": "EIJS"},
    {"label": "Eierlandse Gat boei (ELD1)", "value": "ELD1"},
    {"label": "Empel sluis (EMP1)", "value": "EMP1"},
    {"label": "Empel sluis (EMP2)", "value": "EMP2"},
    {"label": "Empel sluis (EMP3)", "value": "EMP3"},
    {"label": "Empel boven (EMPB)", "value": "EMPB"},
    {"label": "Empel beneden (EMPO)", "value": "EMPO"},
    {"label": "Engelen (ENGL)", "value": "ENGL"},
    {"label": "Europlatform (EPL)", "value": "EPL"},
    {"label": "Europlatform 2 (EPL2)", "value": "EPL2"},
    {"label": "Europahaven (EUR1)", "value": "EUR1"},
    {"label": "F3 platform (F3)", "value": "F3"},
    {"label": "Rotterdamse hoek (FL02)", "value": "FL02"},
    {"label": "Friese kust (FL09)", "value": "FL09"},
    {"label": "Andijk (FL38)", "value": "FL38"},
    {"label": "Markermeer Midden -b (FL42b)", "value": "FL42b"},
    {"label": "Markermeer Midden -o (FL42o)", "value": "FL42o"},
    {"label": "Wieringen Oost (FL48)", "value": "FL48"},
    {"label": "Gaarkeuken Oost (GAKO)", "value": "GAKO"},
    {"label": "Gaarkeuken West (GAKW)", "value": "GAKW"},
    {"label": "Gannet platform 1 (GAN1)", "value": "GAN1"},
    {"label": "Genemuiden (GENE)", "value": "GENE"},
    {"label": "Gennep (GENN)", "value": "GENN"},
    {"label": "Goidschalxoord (GOID)", "value": "GOID"},
    {"label": "Gouda brug (GOUD)", "value": "GOUD"},
    {"label": "Grave boven (GRAB)", "value": "GRAB"},
    {"label": "Grave beneden (GRAV)", "value": "GRAV"},
    {"label": "Grebbe (GREB)", "value": "GREB"},
    {"label": "Groene Riv Pannerden bov (GRPB)", "value": "GRPB"},
    {"label": "Grevelingensluis wind (GRWI)", "value": "GRWI"},
    {"label": "Gat van de stier (GVDS)", "value": "GVDS"},
    {"label": "Haringvliet 10 (HA10)", "value": "HA10"},
    {"label": "Haringvliet 10 (b) (HA10b)", "value": "HA10b"},
    {"label": "Haringvliet 10 (f) (HA10f)", "value": "HA10f"},
    {"label": "Haringvliet 10 (o) (HA10o)", "value": "HA10o"},
    {"label": "Haandrik Kruisbrug (HAAN)", "value": "HAAN"},
    {"label": "Hagestein boven (HAGB)", "value": "HAGB"},
    {"label": "Hagestein beneden (HAGO)", "value": "HAGO"},
    {"label": "Hansweert (HANS)", "value": "HANS"},
    {"label": "Hansweert wind (HAWI)", "value": "HAWI"},
    {"label": "Hansweert wind (b) (HAWIb)", "value": "HAWIb"},
    {"label": "Halfweg boezem (HBZM)", "value": "HBZM"},
    {"label": "Heel beneden (HEEO)", "value": "HEEO"},
    {"label": "Hellevoetsluis (HELL)", "value": "HELL"},
    {"label": "gemaal Hoogland buiten (HGLD)", "value": "HGLD"},
    {"label": "gemaal Hoogland inlaat (HGLDI)", "value": "HGLDI"},
    {"label": "Halfweg gemaal (HGML)", "value": "HGML"},
    {"label": "Hintham boven (HHMB)", "value": "HHMB"},
    {"label": "Hintham beneden (HHMO)", "value": "HHMO"},
    {"label": "Hollandse Kust Noord (HKN)", "value": "HKN"},
    {"label": "Hollandse Kust West Alpha (HKWA)", "value": "HKWA"},
    {"label": "Hollandse Kust West A (HKWA1)", "value": "HKWA1"},
    {"label": "Hollandse Kust West A (HKWA2)", "value": "HKWA2"},
    {"label": "Platform HKZA (HKZA)", "value": "HKZA"},
    {"label": "Platform HKZA 1 (HKZA1)", "value": "HKZA1"},
    {"label": "Platform HKZA 2 (HKZA2)", "value": "HKZA2"},
    {"label": "Honte nabij Sloehaven (HNTE)", "value": "HNTE"},
    {"label": "Honte 2 (Back-up) (HNTE2)", "value": "HNTE2"},
    {"label": "Hoek van Holland (HOEK)", "value": "HOEK"},
    {"label": "Hoorn Terschelling (HOTE)", "value": "HOTE"},
    {"label": "Houtribdijk (HOUD)", "value": "HOUD"},
    {"label": "Houtrib Zuid (HOUZ)", "value": "HOUZ"},
    {"label": "Hondsbroekse Pleij IJssel (HPIJ)", "value": "HPIJ"},
    {"label": "Herenlaak (HRNLK)", "value": "HRNLK"},
    {"label": "Helmond RWZI (HRWZ)", "value": "HRWZ"},
    {"label": "Huibertgat (HUIB)", "value": "HUIB"},
    {"label": "Hoek v Holland NAP -2.5m (HVH25)", "value": "HVH25"},
    {"label": "Hoek v Holland NAP -4.5m (HVH45)", "value": "HVH45"},
    {"label": "Hoek v Holland NAP -9.0m (HVH90)", "value": "HVH90"},
    {"label": "Haringvliet West WS-2m (HVL02)", "value": "HVL02"},
    {"label": "Haringvliet West WS-8m (HVL08)", "value": "HVL08"},
    {"label": "Haringvliet West WS-13m (HVL13)", "value": "HVL13"},
    {"label": "Haringvlietsluizen sch 1 (HVS01)", "value": "HVS01"},
    {"label": "Haringvlietsluizen sch 2 (HVS02)", "value": "HVS02"},
    {"label": "Haringvlietsluizen sch 3 (HVS03)", "value": "HVS03"},
    {"label": "Haringvlietsluizen sch 9 (HVS09)", "value": "HVS09"},
    {"label": "Haringvlietsluizen sch 12 (HVS12)", "value": "HVS12"},
    {"label": "Haringvlietsluizen sch 13 (HVS13)", "value": "HVS13"},
    {"label": "Haringvlietsluizen sch 15 (HVS15)", "value": "HVS15"},
    {"label": "Haringvlietsluizen sch 16 (HVS16)", "value": "HVS16"},
    {"label": "Haringvlietsluizen sch 17 (HVS17)", "value": "HVS17"},
    {"label": "IJgeul (IJGL)", "value": "IJGL"},
    {"label": "IJmuiden Buitenhaven (IJMH)", "value": "IJMH"},
    {"label": "IJmuiden Zuid havenhoofd (IJZ1)", "value": "IJZ1"},
    {"label": "J6 platform (J6)", "value": "J6"},
    {"label": "K14 platform (K14)", "value": "K14"},
    {"label": "Kaapduinen (KADU)", "value": "KADU"},
    {"label": "Kallo (KALO)", "value": "KALO"},
    {"label": "Kamperhoek (KAMH)", "value": "KAMH"},
    {"label": "Kampen (KAMP)", "value": "KAMP"},
    {"label": "Katsberg boven (KATB)", "value": "KATB"},
    {"label": "Katsberg beneden (KATO)", "value": "KATO"},
    {"label": "Kats Zandkreeksluis (KATS)", "value": "KATS"},
    {"label": "Kinderdijk NAP -5m (KDD50)", "value": "KDD50"},
    {"label": "Keeten boei (KEET)", "value": "KEET"},
    {"label": "Keizersveer (KEIZ)", "value": "KEIZ"},
    {"label": "Sluiskil brug (KGTB)", "value": "KGTB"},
    {"label": "Sluiskil brug (b) (KGTBb)", "value": "KGTBb"},
    {"label": "Sluiskil brug (o) (KGTBo)", "value": "KGTBo"},
    {"label": "Sas van Gent (KGTS)", "value": "KGTS"},
    {"label": "Sas van Gent (b) (KGTSb)", "value": "KGTSb"},
    {"label": "Sas van Gent (o) (KGTSo)", "value": "KGTSo"},
    {"label": "KrammersluisOZ1b -1.5mWS (KO1b)", "value": "KO1b"},
    {"label": "KrammersluisOZ1mb -3.5mWS (KO1m)", "value": "KO1m"},
    {"label": "KrammersluisOZ1m -2.5mWS (KO1mb)", "value": "KO1mb"},
    {"label": "KrammersluisOZ1o -5.5mWS (KO1o)", "value": "KO1o"},
    {"label": "Kornwerderzand binnen (KOBI)", "value": "KOBI"},
    {"label": "Kwdznd binnen b(-1,25m) (KOBIb)", "value": "KOBIb"},
    {"label": "Kwdznd binnen o (-4m NAP) (KOBIo)", "value": "KOBIo"},
    {"label": "Kornwerderzand buiten zui (KOBU1)", "value": "KOBU1"},
    {"label": "Kornwerderzand buiten noo (KOBU2)", "value": "KOBU2"},
    {"label": "Kwdznd buiten b (-2m NAP) (KOBUb)", "value": "KOBUb"},
    {"label": "Kwdznd buiten o (-4m NAP) (KOBUo)", "value": "KOBUo"},
    {"label": "Kwdznd Mg b(-2mWS) (KOMb)", "value": "KOMb"},
    {"label": "Kwdznd Mg mb(-5mWS) (KOMmb)", "value": "KOMmb"},
    {"label": "Kwdznd Mg mo(-6mWS) (KOMmo)", "value": "KOMmo"},
    {"label": "Kwdznd Mg o(-6,25mWS) (KOMo)", "value": "KOMo"},
    {"label": "Kwdznd sp b(-1,5mNAP) (KOSb)", "value": "KOSb"},
    {"label": "Kwdznd sp m(-6mNAP) (KOSm)", "value": "KOSm"},
    {"label": "Kwdznd sp mb(-4,5mNAP) (KOSmb)", "value": "KOSmb"},
    {"label": "Kwdznd sp mo(-10,25mNAP) (KOSmo)", "value": "KOSmo"},
    {"label": "Kwdznd sp o(-12mNAP) (KOSo)", "value": "KOSo"},
    {"label": "Kwdznd vg b(-2mNAP) (KOVb)", "value": "KOVb"},
    {"label": "Kwdznd vg mb(-5mNAP) (KOVmb)", "value": "KOVmb"},
    {"label": "Kwdznd vg mo(-7mNAP) (KOVmo)", "value": "KOVmo"},
    {"label": "Kwdznd vg o(-8,5mNAP) (KOVo)", "value": "KOVo"},
    {"label": "Krammerput Boven -1,5m (KPTb)", "value": "KPTb"},
    {"label": "Krammerput Midden_b -8,0m (KPTmb)", "value": "KPTmb"},
    {"label": "Krammerput Midden_o -10,0 (KPTmo)", "value": "KPTmo"},
    {"label": "Krammerput Onder -15,0m (KPTo)", "value": "KPTo"},
    {"label": "Kier 1M WP08 -11mWS (KR1m)", "value": "KR1m"},
    {"label": "Kier 1O WP08 -14,5mWS (KR1o)", "value": "KR1o"},
    {"label": "Kier 2B WP11 -2mWS (KR2b)", "value": "KR2b"},
    {"label": "Kier 2M WP11 -8mWS (KR2m)", "value": "KR2m"},
    {"label": "Kier 2O WP11 -13mWS (KR2o)", "value": "KR2o"},
    {"label": "Kier 3B WP10 -2mWS (KR3b)", "value": "KR3b"},
    {"label": "Kier 3M WP10 -9mWS (KR3m)", "value": "KR3m"},
    {"label": "Kier 3O WP10 -16mWS (KR3o)", "value": "KR3o"},
    {"label": "KIER 4B WP12 -10mWS (KR4b)", "value": "KR4b"},
    {"label": "KIER 4M WP12 -11mWS (KR4m)", "value": "KR4m"},
    {"label": "KIER 4O WP12 -12mWS (KR4o)", "value": "KR4o"},
    {"label": "Krabbersgat Noord (KRAN)", "value": "KRAN"},
    {"label": "Krabbersgat Zuid (KRAZ)", "value": "KRAZ"},
    {"label": "Krammer Laagbekken  (b) (KRBLb)", "value": "KRBLb"},
    {"label": "Krammer Laagbekken (o) (KRBLo)", "value": "KRBLo"},
    {"label": "Krimpen a/d Lek (KRIL)", "value": "KRIL"},
    {"label": "Krimpen a/d IJssel (KRIY)", "value": "KRIY"},
    {"label": "Krammer Noord (KRND)", "value": "KRND"},
    {"label": "Krammersluizen West (KRSL)", "value": "KRSL"},
    {"label": "Krimpen IJssel NAP -4.0m (KRY40)", "value": "KRY40"},
    {"label": "Krimpen IJssel NAP -5.5m (KRY55)", "value": "KRY55"},
    {"label": "Krammersluis volkerakzijd (KV1b)", "value": "KV1b"},
    {"label": "Krammersluis volkerakzijd (KV1o)", "value": "KV1o"},
    {"label": "Krammersluis volkerakzijd (KV2b)", "value": "KV2b"},
    {"label": "Krammersluis volkerakzijd (KV2o)", "value": "KV2o"},
    {"label": "Katwijk gemaal (KWGM)", "value": "KWGM"},
    {"label": "L9 platform (L9)", "value": "L9"},
    {"label": "Lauwersoog (LAUW)", "value": "LAUW"},
    {"label": "Lemmer Boezem (LBOE)", "value": "LBOE"},
    {"label": "Leeuwarden (LEEU)", "value": "LEEU"},
    {"label": "Lichteiland Goeree (LEG)", "value": "LEG"},
    {"label": "Lekhaven NAP -2.5m (LEK25)", "value": "LEK25"},
    {"label": "Lekhaven NAP -5.0m (LEK50)", "value": "LEK50"},
    {"label": "Lekhaven NAP -7.0m (LEK70)", "value": "LEK70"},
    {"label": "Lage Licht (LGL1)", "value": "LGL1"},
    {"label": "Liefkenshoek (LIEF)", "value": "LIEF"},
    {"label": "Lemmer IJsselmeer (LIJM)", "value": "LIJM"},
    {"label": "Linne boven (LINB)", "value": "LINB"},
    {"label": "Lith boven (LITB)", "value": "LITB"},
    {"label": "Inlaat Landsweijer (LNDW)", "value": "LNDW"},
    {"label": "Lobith Haven (LOBH)", "value": "LOBH"},
    {"label": "Loozen (LOOZ)", "value": "LOOZ"},
    {"label": "Lemmer Teroelsterkolk (LTER)", "value": "LTER"},
    {"label": "Teroelsterkolk buiten (LTRY)", "value": "LTRY"},
    {"label": "Lemmer Woudagemaal (LWOU)", "value": "LWOU"},
    {"label": "Maaseik (MAAE)", "value": "MAAE"},
    {"label": "Maarssen (MAAR)", "value": "MAAR"},
    {"label": "Maassluis (MAAS)", "value": "MAAS"},
    {"label": "sluis Makkum buiten -130 (MAKBb)", "value": "MAKBb"},
    {"label": "sluis Makkum buiten -180 (MAKBo)", "value": "MAKBo"},
    {"label": "Marknesse (MARK)", "value": "MARK"},
    {"label": "Markelose brug (MARKB)", "value": "MARKB"},
    {"label": "Meeswijk veer (MEESW)", "value": "MEESW"},
    {"label": "Megen (MEGE)", "value": "MEGE"},
    {"label": "Meppelerdiep km 2.5 (MEP25)", "value": "MEP25"},
    {"label": "Middelharnis MB NAP -2m (MH020)", "value": "MH020"},
    {"label": "Middelharnis MB NAP -8m (MH080)", "value": "MH080"},
    {"label": "Middelharnis MB NAP -15m (MH150)", "value": "MH150"},
    {"label": "Millingen a/d Rijn (MILL)", "value": "MILL"},
    {"label": "Marina Kralendijk boven (MKRAb)", "value": "MKRAb"},
    {"label": "Marina Kralendijk onder (MKRAo)", "value": "MKRAo"},
    {"label": "Maeslantkering zeezijde N (MLK1)", "value": "MLK1"},
    {"label": "Maeslantkering zeezijde Z (MLK2)", "value": "MLK2"},
    {"label": "Maeslantkering geleidetor (MLKZ)", "value": "MLKZ"},
    {"label": "Maasgeul Maasvlakte Noord (MMND)", "value": "MMND"},
    {"label": "Maasmond Papegaaiebek (MMPB)", "value": "MMPB"},
    {"label": "Monding Nieuwe Haven (MNHV)", "value": "MNHV"},
    {"label": "Moerdijkbrug 000 (MO000)", "value": "MO000"},
    {"label": "Moerdijkbrug 030 (MO030)", "value": "MO030"},
    {"label": "Moerdijkbrug 045 (MO045)", "value": "MO045"},
    {"label": "Moerdijkbrug 060 (MO060)", "value": "MO060"},
    {"label": "Moerdijk (MOER)", "value": "MOER"},
    {"label": "Mond der Vecht (MOND)", "value": "MOND"},
    {"label": "Marollegat (MRG)", "value": "MRG"},
    {"label": "Marollegat (b) (MRGb)", "value": "MRGb"},
    {"label": "Marollegat (o) (MRGo)", "value": "MRGo"},
    {"label": "Mauriksewetering (MRSW)", "value": "MRSW"},
    {"label": "Muiden brug (MUIB)", "value": "MUIB"},
    {"label": "IJgeul Munitiestort 1 (MUN1)", "value": "MUN1"},
    {"label": "IJgeul Munitiestort 2 (MUN2)", "value": "MUN2"},
    {"label": "Maasvlakte Slufter (MVSL)", "value": "MVSL"},
    {"label": "Naviduct Noord (NAVN)", "value": "NAVN"},
    {"label": "Naviduct Zuid (NAVZ)", "value": "NAVZ"},
    {"label": "NDSM-werf (o) (NDS1)", "value": "NDS1"},
    {"label": "NDSM-werf (b) (NDS2)", "value": "NDS2"},
    {"label": "Neer (NEER)", "value": "NEER"},
    {"label": "Negenoord-West (NEGW)", "value": "NEGW"},
    {"label": "Nes (NES)", "value": "NES"},
    {"label": "Nes 2 (golven) (NES2)", "value": "NES2"},
    {"label": "Nieuw Beerta (NIBE)", "value": "NIBE"},
    {"label": "Nijmegen haven (NIJM)", "value": "NIJM"},
    {"label": "Nijkerk Oost (NIJO)", "value": "NIJO"},
    {"label": "Nelson platform1 (NLS1)", "value": "NLS1"},
    {"label": "ADM Noordervaart (NVAA)", "value": "NVAA"},
    {"label": "Nieuwegein (NWGN)", "value": "NWGN"},
    {"label": "Nieuwe Statenzijl (NWST)", "value": "NWST"},
    {"label": "Den Oever binnen (OEBI)", "value": "OEBI"},
    {"label": "Den Oever binnen b -1,25 (OEBIb)", "value": "OEBIb"},
    {"label": "Den Oever binnen o-4m (OEBIo)", "value": "OEBIo"},
    {"label": "Den Oever buiten b -2m (OEBUb)", "value": "OEBUb"},
    {"label": "Den Oever buiten o-4m (OEBUo)", "value": "OEBUo"},
    {"label": "Hengelo Oelerbrug (OELB)", "value": "OELB"},
    {"label": "Den Oever sp b(-1,5mWS) (OESb)", "value": "OESb"},
    {"label": "Den Oever sp mb(-4,5mWS) (OESmb)", "value": "OESmb"},
    {"label": "Den Oever sp mo(-5,6mWS) (OESmo)", "value": "OESmo"},
    {"label": "Den Oever sp o(-6,7mWS) (OESo)", "value": "OESo"},
    {"label": "Den Oever vg b(-2mNAP) (OEVb)", "value": "OEVb"},
    {"label": "Den Oever vg mb(-4mNAP) (OEVmb)", "value": "OEVmb"},
    {"label": "Den Oever vg mo(-5,5mNAP) (OEVmo)", "value": "OEVmo"},
    {"label": "Den Oever vg o(-7m NAP) (OEVo)", "value": "OEVo"},
    {"label": "Olst (OLST)", "value": "OLST"},
    {"label": "Ommen Hesselmulertbrug (OMMH)", "value": "OMMH"},
    {"label": "Ommen Ommerkanaal (OMMK)", "value": "OMMK"},
    {"label": "Oostersluis (OOSS)", "value": "OOSS"},
    {"label": "Oosterschelde 11 (OS11)", "value": "OS11"},
    {"label": "Oosterschelde 11 (b) (OS11b)", "value": "OS11b"},
    {"label": "Oosterschelde 14 (OS14)", "value": "OS14"},
    {"label": "Oosterschelde 4 (OS4)", "value": "OS4"},
    {"label": "Oosterschelde 4 (b) (OS4b)", "value": "OS4b"},
    {"label": "Oosterschelde 4 (o) (OS4o)", "value": "OS4o"},
    {"label": "Oosterscheldeker. Hammen (OSKH)", "value": "OSKH"},
    {"label": "Oosterscheldeker. Roompot (OSKR)", "value": "OSKR"},
    {"label": "Oosterscheldeker. Schaar (OSKS)", "value": "OSKS"},
    {"label": "Ovl v Bosscherveld QH (OVB)", "value": "OVB"},
    {"label": "Overloop van Hansweert (OVHA)", "value": "OVHA"},
    {"label": "Overloop v. Hansweert (b) (OVHAb)", "value": "OVHAb"},
    {"label": "Overloop v. Hansweert gol (OVHW)", "value": "OVHW"},
    {"label": "Overloop van Valkenisse (OVVA)", "value": "OVVA"},
    {"label": "Oude Westereems Noordboei (OWEN)", "value": "OWEN"},
    {"label": "Oude Westereems Zuidboei (OWEZ)", "value": "OWEZ"},
    {"label": "P11 platform (P11)", "value": "P11"},
    {"label": "Pannerdens kanaal (PANK)", "value": "PANK"},
    {"label": "Pannerdense kop (PANN)", "value": "PANN"},
    {"label": "Plazabeach Terminal (PBEA)", "value": "PBEA"},
    {"label": "Plaat van Oude Tonge (b) (PLOTb)", "value": "PLOTb"},
    {"label": "Plaat van Oude Tonge (o) (PLOTo)", "value": "PLOTo"},
    {"label": "Poeldonk boven - ZWV (POEB)", "value": "POEB"},
    {"label": "Poeldonk beneden - Aa (POEO)", "value": "POEO"},
    {"label": "Pas van Terneuzen boei (PVT)", "value": "PVT"},
    {"label": "Ramspolkering Ketelmeerzi (RAMK)", "value": "RAMK"},
    {"label": "Ramspolbrug (RAMS)", "value": "RAMS"},
    {"label": "Roermond boven (ROER)", "value": "ROER"},
    {"label": "Roggenplaat (ROGP)", "value": "ROGP"},
    {"label": "Rotterdam Luchthaven (ROT1)", "value": "ROT1"},
    {"label": "Rotterdam Geulhaven (ROT2)", "value": "ROT2"},
    {"label": "Rotterdam (ROTT)", "value": "ROTT"},
    {"label": "Rozenburgse Sluis (ROZS)", "value": "ROZS"},
    {"label": "Beergat Radarpost 4 (RP04)", "value": "RP04"},
    {"label": "Caland West Radarpost 5 (RP05)", "value": "RP05"},
    {"label": "Caland Midden Radarpost 6 (RP06)", "value": "RP06"},
    {"label": "Rozenburg Radarpost 8 (RP08)", "value": "RP08"},
    {"label": "Geulhaven Radarpost 10 (RP10)", "value": "RP10"},
    {"label": "Waalhaven Radarpost 19 (RP19)", "value": "RP19"},
    {"label": "Kuip2 Radarpost 23 (RP23)", "value": "RP23"},
    {"label": "Caland Oost Radarpost 32 (RP32)", "value": "RP32"},
    {"label": "Roompot binnen (SVKO) (RPBI)", "value": "RPBI"},
    {"label": "Roompotsluis (SVKO) (RPSL)", "value": "RPSL"},
    {"label": "Rijswijk Betuwepand (RSWK)", "value": "RSWK"},
    {"label": "Rotem Maas (RTEM)", "value": "RTEM"},
    {"label": "Rotem Bichterweerd (RTMB)", "value": "RTMB"},
    {"label": "Reevesluis noord (RVN)", "value": "RVN"},
    {"label": "Randzelgat Noord boei (RZGN1)", "value": "RZGN1"},
    {"label": "Sluis 4 beneden (S04O)", "value": "S04O"},
    {"label": "Sluis 5 beneden (S05O)", "value": "S05O"},
    {"label": "Sluis 9 boven (S09B)", "value": "S09B"},
    {"label": "Sluis 9 spuiduiker (S09S)", "value": "S09S"},
    {"label": "Sluis 10 beneden (S10O)", "value": "S10O"},
    {"label": "Sluis 13 ADM (S13A)", "value": "S13A"},
    {"label": "Sluis 13 boven (S13B)", "value": "S13B"},
    {"label": "Sluis 13 beneden (S13O)", "value": "S13O"},
    {"label": "Sluis 15 boven (S15B)", "value": "S15B"},
    {"label": "Sluis 16 boven (S16B)", "value": "S16B"},
    {"label": "Sluis 16 beneden (S16O)", "value": "S16O"},
    {"label": "Sluis 22 beneden (S22O)", "value": "S22O"},
    {"label": "Sluis 23 boven (S23B)", "value": "S23B"},
    {"label": "Sluis 23 beneden (S23O)", "value": "S23O"},
    {"label": "Sluis 24 boven (S24B)", "value": "S24B"},
    {"label": "Sluis 24 beneden (S24O)", "value": "S24O"},
    {"label": "Sambeek boven (SAMB)", "value": "SAMB"},
    {"label": "Schabbert boven (SCAB)", "value": "SCAB"},
    {"label": "Scheveningen (SCHE)", "value": "SCHE"},
    {"label": "Schiermonnikoog (SCHI)", "value": "SCHI"},
    {"label": "Schaar Stroomgat (SCHS)", "value": "SCHS"},
    {"label": "Schellingwouderbrug (SCHWB)", "value": "SCHWB"},
    {"label": "Scheeresluis beneden (SCSO)", "value": "SCSO"},
    {"label": "Spaarndam boezem (SDBN)", "value": "SDBN"},
    {"label": "Spaarndam gemaal (SDGM)", "value": "SDGM"},
    {"label": "Sint Pieter noord (SINT)", "value": "SINT"},
    {"label": "Slaak Noord boven (SKNDb)", "value": "SKNDb"},
    {"label": "Slaak Noord midden (SKNDm)", "value": "SKNDm"},
    {"label": "Slaak Noord onder (SKNDo)", "value": "SKNDo"},
    {"label": "Slaak Oost (SKOT)", "value": "SKOT"},
    {"label": "Slaak Zuid (SKZD)", "value": "SKZD"},
    {"label": "Slochtersluis boven (SLBV)", "value": "SLBV"},
    {"label": "Zwartsluis gemaal pomp mi (SLGPM)", "value": "SLGPM"},
    {"label": "Zwartsluis gemaal pomp O (SLGPO)", "value": "SLGPO"},
    {"label": "Zwartsluis gemaal pomp W (SLGPW)", "value": "SLGPW"},
    {"label": "Smeermaas (SMEE)", "value": "SMEE"},
    {"label": "Schiermonnikoog Noord boe (SMN1)", "value": "SMN1"},
    {"label": "Schiermonnikoog Westgat b (SMWG)", "value": "SMWG"},
    {"label": "Spuisluis Oude Eemskanaal (SOEB)", "value": "SOEB"},
    {"label": "Spaarnd.polder NAP -1.4m (SPA14)", "value": "SPA14"},
    {"label": "Spaarnd.polder NAP -6.4m (SPA64)", "value": "SPA64"},
    {"label": "Spijkenisserbrug West (SPBR)", "value": "SPBR"},
    {"label": "Stroommeetpaal Eemshaven (SPE)", "value": "SPE"},
    {"label": "Panheel boven - ZWV (SPHB)", "value": "SPHB"},
    {"label": "Spijkenisserbrug NAP-2.5m (SPI25)", "value": "SPI25"},
    {"label": "Spijkenisserbrug NAP-4.5m (SPI45)", "value": "SPI45"},
    {"label": "Spijkenisserbrug NAP-9.0m (SPI90)", "value": "SPI90"},
    {"label": "Spaanjerd (SPNJD)", "value": "SPNJD"},
    {"label": "Middelharnis Spui NAP -1m (SPU10)", "value": "SPU10"},
    {"label": "Middelharnis Spui NAP -5m (SPU50)", "value": "SPU50"},
    {"label": "Bathse spuikan. Inloop (b (SPUIb)", "value": "SPUIb"},
    {"label": "Bathse spuikan. Inloop (o (SPUIo)", "value": "SPUIo"},
    {"label": "IJgeul stroommeetpaal (SPY)", "value": "SPY"},
    {"label": "IJgeul SMP 2 (bus) (SPY2)", "value": "SPY2"},
    {"label": "Sint Annaland (STAN)", "value": "STAN"},
    {"label": "Stavenisse (STAV)", "value": "STAV"},
    {"label": "Stellendam binnen WS-2m (STB02)", "value": "STB02"},
    {"label": "Stellendam binnen WS-6m (STB06)", "value": "STB06"},
    {"label": "Stellendam binnen WS-11m (STB11)", "value": "STB11"},
    {"label": "Stellendam buiten boven (STBUb)", "value": "STBUb"},
    {"label": "De Steeg (STEE)", "value": "STEE"},
    {"label": "Steurgat (STGT)", "value": "STGT"},
    {"label": "Stortemelk boei (STM1)", "value": "STM1"},
    {"label": "Stortemelk Oost (STMO1)", "value": "STMO1"},
    {"label": "Stavoren (STVO)", "value": "STVO"},
    {"label": "Surinamekade (SURI)", "value": "SURI"},
    {"label": "Schellingw.brug NAP -2.8m (SWB28)", "value": "SWB28"},
    {"label": "Termunterzijl (TERM)", "value": "TERM"},
    {"label": "Terschelling Noordzee (TERS)", "value": "TERS"},
    {"label": "Texel Noordzee (TEXE)", "value": "TEXE"},
    {"label": "Terherne Boezem Oostzijde (THBO)", "value": "THBO"},
    {"label": "Terherne Boezem Westzijde (THBW)", "value": "THBW"},
    {"label": "Tolhuissluis (THSL)", "value": "THSL"},
    {"label": "Tiel Waal (TIEW)", "value": "TIEW"},
    {"label": "Tiel Waal (RAM) (TIEWB)", "value": "TIEWB"},
    {"label": "Terneuzen Westsluis (TNWS)", "value": "TNWS"},
    {"label": "Inlaat Teersesluispolder (TPOL)", "value": "TPOL"},
    {"label": "Breda Trambrug (TRMB)", "value": "TRMB"},
    {"label": "Terneuzen Westsluis ZZ (b (TWZZb)", "value": "TWZZb"},
    {"label": "Terneuzen Westsluis ZZ (o (TWZZo)", "value": "TWZZo"},
    {"label": "Trintelzand (TZND)", "value": "TZND"},
    {"label": "Trintelzand boven (TZNDb)", "value": "TZNDb"},
    {"label": "Trintelzand onder (TZNDo)", "value": "TZNDo"},
    {"label": "Uithuizerwad 2 (UHW2)", "value": "UHW2"},
    {"label": "Uithuizerwad 3 (UHW3)", "value": "UHW3"},
    {"label": "Uithuizerwad (UHWD)", "value": "UHWD"},
    {"label": "Uikhoven (UIKHV)", "value": "UIKHV"},
    {"label": "Vechterweerd beneden (VECO)", "value": "VECO"},
    {"label": "Volkerakgat 2 (VG02)", "value": "VG02"},
    {"label": "Volkerakgat 3 (VG03)", "value": "VG03"},
    {"label": "Volkerak Galathee (VK)", "value": "VK"},
    {"label": "Volkerak Galathee (o) (VKo)", "value": "VKo"},
    {"label": "Vlieland (VLI1)", "value": "VLI1"},
    {"label": "Velserkom b WS3 -1 (VLSKb)", "value": "VLSKb"},
    {"label": "Velserkom m WS3 -6 (VLSKm)", "value": "VLSKm"},
    {"label": "Velserkom o WS3 -8 (VLSKo)", "value": "VLSKo"},
    {"label": "VM3 Zandkreeksluis (VM3)", "value": "VM3"},
    {"label": "Veersemeer 4 Oranjeplaat (VM4)", "value": "VM4"},
    {"label": "VM4 Oranjeplaat (b) (VM4b)", "value": "VM4b"},
    {"label": "VM4 Oranjeplaat (o) (VM4o)", "value": "VM4o"},
    {"label": "VM5 Schotsman (b) (VM5b)", "value": "VM5b"},
    {"label": "VM5 Schotsman (o) (VM5o)", "value": "VM5o"},
    {"label": "Volkerak Noord (b) (VOLKb)", "value": "VOLKb"},
    {"label": "Volkerak Noord (o) (VOLKo)", "value": "VOLKo"},
    {"label": "Vossenbeemd Helmond (VOSB)", "value": "VOSB"},
    {"label": "Nieuw Vossemeer (VOSM)", "value": "VOSM"},
    {"label": "Nieuw Vossemeer (b) (VOSMb)", "value": "VOSMb"},
    {"label": "Nieuw Vossemeer (o) (VOSMo)", "value": "VOSMo"},
    {"label": "Vlakte v/d Raan (VR)", "value": "VR"},
    {"label": "Vlakte v/d Raan (b) (VRb)", "value": "VRb"},
    {"label": "Vlakte v/d Raan (o) (VRo)", "value": "VRo"},
    {"label": "Vuren (VURE)", "value": "VURE"},
    {"label": "Walsoorden (WALS)", "value": "WALS"},
    {"label": "Weesp (WEES)", "value": "WEES"},
    {"label": "Westereems Oost boei (WEO1)", "value": "WEO1"},
    {"label": "Westervoort (WEST)", "value": "WEST"},
    {"label": "Inlaat Weurt (WEUR)", "value": "WEUR"},
    {"label": "Westereems West boei (WEW1)", "value": "WEW1"},
    {"label": "Wieldrecht (WIED)", "value": "WIED"},
    {"label": "Wielingen Noord (WIEL)", "value": "WIEL"},
    {"label": "Wierumergronden (WIER)", "value": "WIER"},
    {"label": "Wijdenes (WIJD)", "value": "WIJD"},
    {"label": "Wijhe (WIJH)", "value": "WIJH"},
    {"label": "Wijk bij Duurstede (WIJK)", "value": "WIJK"},
    {"label": "Wilhelminadorp (WILH)", "value": "WILH"},
    {"label": "Westkapelle (WKAP)", "value": "WKAP"},
    {"label": "Waalwijk (WLWK)", "value": "WLWK"},
    {"label": "Zaltbommel (ZALT)", "value": "ZALT"},
    {"label": "Zeelandbrug wind (ZBWI)", "value": "ZBWI"},
    {"label": "Zijkanaal C (NAP -140) (ZC14)", "value": "ZC14"},
    {"label": "Zijkanaal C (NAP -440) (ZC44)", "value": "ZC44"},
    {"label": "Zaangemaal (ZGML)", "value": "ZGML"},
    {"label": "Zandkreekdam (ZKD)", "value": "ZKD"},
    {"label": "Zwartsluis buiten (ZWBU)", "value": "ZWBU"},
]