"""Locations for the RWS waterinfo integration."""

CONF_LOC_OPTIONS = [
    {"label": "A12 platform", "value": "A12"},
    {"label": "Schijndelse loop", "value": "AA03"},
    {"label": "Almen", "value": "ALME"},
    {"label": "Amaliahaven", "value": "AMHV"},
    {"label": "Amerongen boven", "value": "AMRB"},
    {"label": "Amerongen beneden", "value": "AMRO"},
    {"label": "Antwerps kanaalpand", "value": "ANKA"},
    {"label": "Antwerps kanaalpand (b)", "value": "ANKAb"},
    {"label": "Antwerps kanaalpand (o)", "value": "ANKAo"},
    {"label": "Antwerpen", "value": "ANTW"},
    {"label": "Arnhem", "value": "ARNH"},
    {"label": "AWG platform", "value": "AWG"},
    {"label": "Baalhoek", "value": "BAAL"},
    {"label": "Baalhoek (b)", "value": "BAALb"},
    {"label": "Baalhoek (o)", "value": "BAALo"},
    {"label": "Bath", "value": "BATH"},
    {"label": "Bathse brug Deltanuts", "value": "BBDT"},
    {"label": "Bathse brug Deltanuts (b)", "value": "BBDTb"},
    {"label": "Bathse brug Deltanuts (o)", "value": "BBDTo"},
    {"label": "Bergsediepsluis", "value": "BDSL"},
    {"label": "Bergsediepsluis wind", "value": "BDWI"},
    {"label": "Belfeld boven", "value": "BELB"},
    {"label": "Belfeld beneden", "value": "BELF"},
    {"label": "Bernisse NAP -3m", "value": "BER30"},
    {"label": "Berkhout", "value": "BERK"},
    {"label": "Bernisse Zuidland", "value": "BERN"},
    {"label": "Brouwershavense Gat 2", "value": "BG2"},
    {"label": "Brouwershavense Gat 2 (b)", "value": "BG2b"},
    {"label": "Brouwershavense Gat 2 (o)", "value": "BG2o"},
    {"label": "Brouwershavense Gat 8", "value": "BG8"},
    {"label": "Brouwershavense Gat 8 (b)", "value": "BG8b"},
    {"label": "Brouwershavense Gat 8 (o)", "value": "BG8o"},
    {"label": "Berghaven H v Holland", "value": "BGH1"},
    {"label": "Borgharen Julianakanaal 2", "value": "BHJE"},
    {"label": "Binnen Kievitswaard", "value": "BKWD"},
    {"label": "Blaarthem boven", "value": "BLAB"},
    {"label": "Blaarthem Gender", "value": "BLAG"},
    {"label": "Beuningengemaal", "value": "BNGG"},
    {"label": "Bommenede 1", "value": "BOM1"},
    {"label": "Bommenede 1 (b)", "value": "BOM1b"},
    {"label": "Bommenede 1 (o)", "value": "BOM1o"},
    {"label": "Beerenplaat NAP -2m", "value": "BOM20"},
    {"label": "Borgharen boven", "value": "BORB"},
    {"label": "Borgharen Dorp", "value": "BORD"},
    {"label": "Borgharen Julianakanaal", "value": "BORJ"},
    {"label": "Borssele", "value": "BORS"},
    {"label": "Brienenoordbrug NAP-2.5 m", "value": "BRB25"},
    {"label": "Brienenoordbrug NAP-6.5 m", "value": "BRB65"},
    {"label": "Breskens Handelshaven", "value": "BRES"},
    {"label": "Burgumerdaam Boezem", "value": "BRGD"},
    {"label": "Stuw Borgsweer", "value": "BRGW"},
    {"label": "Brouwersdam 2 buiten Zuid", "value": "BRO2"},
    {"label": "Brouwersdam 6 binnen Zuid", "value": "BRO6"},
    {"label": "Borssele Alpha", "value": "BSA"},
    {"label": "Benedensas Sluis", "value": "BSASS"},
    {"label": "Bathse spuisluis D", "value": "BSBSD"},
    {"label": "Bathse spuisluis Ws", "value": "BSBSW"},
    {"label": "Bathse spuisluis kanaal", "value": "BSBSZ"},
    {"label": "Buitenbanken west", "value": "BUBW"},
    {"label": "Buggenum", "value": "BUGG"},
    {"label": "Buitenhuizen", "value": "BUIT"},
    {"label": "Bunde", "value": "BUND"},
    {"label": "Cadzand", "value": "CADZ"},
    {"label": "Cadzand wind", "value": "CAWI"},
    {"label": "Geul Cotessen", "value": "COTS"},
    {"label": "Crevecoeur", "value": "CREV"},
    {"label": "Culemborg brug", "value": "CULB"},
    {"label": "D15 platform", "value": "D15"},
    {"label": "De Kooy", "value": "DEKO"},
    {"label": "Delden boven", "value": "DELB"},
    {"label": "Delden beneden", "value": "DELO"},
    {"label": "Den Helder", "value": "DENH"},
    {"label": "Deurloo", "value": "DEUR"},
    {"label": "Deventer", "value": "DEVE"},
    {"label": "Diemen (NAP -1.4m)", "value": "DIE14"},
    {"label": "Diemen (NAP -6.5m)", "value": "DIE65"},
    {"label": "Delfzijl", "value": "DLFZ"},
    {"label": "Drielandenpunt", "value": "DLPT"},
    {"label": "Inlaat Son en Breugel", "value": "DM13"},
    {"label": "Inlaat Beekse Waterloop", "value": "DM14"},
    {"label": "Den Helder Veersteiger 2", "value": "DNHV"},
    {"label": "Dodewaard", "value": "DODE"},
    {"label": "Doesburg brug", "value": "DOES"},
    {"label": "Doorslag", "value": "DOOR"},
    {"label": "Domburger Rassen", "value": "DORA"},
    {"label": "Dordrecht", "value": "DORD"},
    {"label": "Dorkwerd", "value": "DORK"},
    {"label": "Driel boven", "value": "DRIB"},
    {"label": "Driel beneden", "value": "DRIO"},
    {"label": "Duivelseiland 000", "value": "DU000"},
    {"label": "Duivelseiland 015", "value": "DU015"},
    {"label": "Duivelseiland 030", "value": "DU030"},
    {"label": "Duivelseiland 045", "value": "DU045"},
    {"label": "Duivelseiland 060", "value": "DU060"},
    {"label": "Duivelseiland 075", "value": "DU075"},
    {"label": "Duivelseiland 090", "value": "DU090"},
    {"label": "Duivelseiland  105", "value": "DU105"},
    {"label": "Duivelseiland  120", "value": "DU120"},
    {"label": "Duivelseiland  135", "value": "DU135"},
    {"label": "Duivelseiland  150", "value": "DU150"},
    {"label": "Duivelseiland  165", "value": "DU165"},
    {"label": "Duivelseiland  180", "value": "DU180"},
    {"label": "Duivelseiland  195", "value": "DU195"},
    {"label": "Duivelseiland  210", "value": "DU210"},
    {"label": "Duivelseiland  225", "value": "DU225"},
    {"label": "Duivelseiland  240", "value": "DU240"},
    {"label": "Duivelseiland  255", "value": "DU255"},
    {"label": "Duivelseiland  270", "value": "DU270"},
    {"label": "Duivelseiland  285", "value": "DU285"},
    {"label": "Duivelseiland  300", "value": "DU300"},
    {"label": "Eurogeul DWE", "value": "DWE1"},
    {"label": "Eurogeul E13", "value": "E13"},
    {"label": "Echt", "value": "ECHT"},
    {"label": "Edam", "value": "EDAM"},
    {"label": "Eefde boven", "value": "EEFB"},
    {"label": "Eefde beneden", "value": "EEFD"},
    {"label": "Eefde beneden", "value": "EEFO"},
    {"label": "Eemdijk", "value": "EEMDK"},
    {"label": "Eibersburen", "value": "EIBN"},
    {"label": "Eijsden grens", "value": "EIJS"},
    {"label": "Eijsden ponton", "value": "EIJSP"},
    {"label": "Eisden Mazenhove", "value": "EISM"},
    {"label": "Elburgerbrug", "value": "ELBB"},
    {"label": "Eierlandse Gat boei", "value": "ELD1"},
    {"label": "Elsloo", "value": "ELSL"},
    {"label": "Empel sluis", "value": "EMP1"},
    {"label": "Empel sluis", "value": "EMP2"},
    {"label": "Empel sluis", "value": "EMP3"},
    {"label": "Empel boven", "value": "EMPB"},
    {"label": "Empel beneden", "value": "EMPO"},
    {"label": "Engelen", "value": "ENGL"},
    {"label": "Europlatform", "value": "EPL"},
    {"label": "Europlatform 2", "value": "EPL2"},
    {"label": "Europahaven", "value": "EUR1"},
    {"label": "F3 platform", "value": "F3"},
    {"label": "Rotterdamse hoek", "value": "FL02"},
    {"label": "Friese kust", "value": "FL09"},
    {"label": "Andijk", "value": "FL38"},
    {"label": "Markermeer Midden -b", "value": "FL42b"},
    {"label": "Markermeer Midden -o", "value": "FL42o"},
    {"label": "Wieringen Oost", "value": "FL48"},
    {"label": "Galgenkampsbrug", "value": "GALG"},
    {"label": "Gannet platform 1", "value": "GAN1"},
    {"label": "Genemuiden", "value": "GENE"},
    {"label": "Gennep", "value": "GENN"},
    {"label": "Goidschalxoord", "value": "GOID"},
    {"label": "Gouda brug", "value": "GOUD"},
    {"label": "Grave boven", "value": "GRAB"},
    {"label": "Grave beneden", "value": "GRAV"},
    {"label": "Grebbe", "value": "GREB"},
    {"label": "Groene Riv Pannerden bov", "value": "GRPB"},
    {"label": "Groene Riv Pannerden ben", "value": "GRPO"},
    {"label": "Grevelingensluis wind", "value": "GRWI"},
    {"label": "Gat van de stier", "value": "GVDS"},
    {"label": "Haringvliet 10", "value": "HA10"},
    {"label": "Haringvliet 10 (b)", "value": "HA10b"},
    {"label": "Haringvliet 10 (e)", "value": "HA10e"},
    {"label": "Haringvliet 10 (f)", "value": "HA10f"},
    {"label": "Haringvliet 10 (o)", "value": "HA10o"},
    {"label": "Haandrik Kruisbrug", "value": "HAAN"},
    {"label": "Hagestein boven", "value": "HAGB"},
    {"label": "Hagestein beneden", "value": "HAGO"},
    {"label": "Hansweert", "value": "HANS"},
    {"label": "Harlingen", "value": "HARL"},
    {"label": "Hansweert wind", "value": "HAWI"},
    {"label": "Hansweert wind (b)", "value": "HAWIb"},
    {"label": "Heel boven", "value": "HEEB"},
    {"label": "Heel beneden", "value": "HEEO"},
    {"label": "Heesbeen", "value": "HEES"},
    {"label": "Hellevoetsluis", "value": "HELL"},
    {"label": "Hengelo boven", "value": "HENB"},
    {"label": "Hengelo Koppelleiding", "value": "HENK"},
    {"label": "Hengelo beneden", "value": "HENO"},
    {"label": "gemaal Hoogland buiten", "value": "HGLD"},
    {"label": "gemaal Hoogland inlaat", "value": "HGLDI"},
    {"label": "Hintham boven", "value": "HHMB"},
    {"label": "Hintham beneden", "value": "HHMO"},
    {"label": "Hollandse Kust Noord", "value": "HKN"},
    {"label": "Hollandse Kust West Alpha", "value": "HKWA"},
    {"label": "Hollandse Kust West A", "value": "HKWA1"},
    {"label": "Hollandse Kust West A", "value": "HKWA2"},
    {"label": "Platform HKZA", "value": "HKZA"},
    {"label": "Platform HKZA 1", "value": "HKZA1"},
    {"label": "Platform HKZA 2", "value": "HKZA2"},
    {"label": "HKZ Windpark Noord", "value": "HKZWN"},
    {"label": "HKZ Windpark Zuid", "value": "HKZWZ"},
    {"label": "Honte nabij Sloehaven", "value": "HNTE"},
    {"label": "Honte 2 (Back-up)", "value": "HNTE2"},
    {"label": "Hoek van Holland", "value": "HOEK"},
    {"label": "Hollandse brug", "value": "HOLB"},
    {"label": "Holwerd", "value": "HOLW"},
    {"label": "Hoorn Terschelling", "value": "HOTE"},
    {"label": "Houtribdijk", "value": "HOUD"},
    {"label": "Houtrib Noord", "value": "HOUN"},
    {"label": "Houtrib Zuid", "value": "HOUZ"},
    {"label": "Happen Hennip", "value": "HPHP"},
    {"label": "Hondsbroekse Pleij hwgeul", "value": "HPHW"},
    {"label": "Hondsbroekse Pleij IJssel", "value": "HPIJ"},
    {"label": "Herenlaak", "value": "HRNLK"},
    {"label": "Helmond RWZI - boven", "value": "HRWB"},
    {"label": "Helmond RWZI", "value": "HRWZ"},
    {"label": "Huibertgat", "value": "HUIB"},
    {"label": "Haringvlietsluizen buiten", "value": "HVBU"},
    {"label": "Hoek v Holland NAP -2.5m", "value": "HVH25"},
    {"label": "Hoek v Holland NAP -4.5m", "value": "HVH45"},
    {"label": "Hoek v Holland NAP -9.0m", "value": "HVH90"},
    {"label": "Haringvliet West WS-2m", "value": "HVL02"},
    {"label": "Haringvliet West WS-8m", "value": "HVL08"},
    {"label": "Haringvliet West WS-13m", "value": "HVL13"},
    {"label": "Haringvlietsluizen sch 1", "value": "HVS01"},
    {"label": "Haringvlietsluizen sch 2", "value": "HVS02"},
    {"label": "Haringvlietsluizen sch 3", "value": "HVS03"},
    {"label": "Haringvlietsluizen sch 4", "value": "HVS04"},
    {"label": "Haringvlietsluizen sch 5", "value": "HVS05"},
    {"label": "Haringvlietsluizen sch 6", "value": "HVS06"},
    {"label": "Haringvlietsluizen sch 7", "value": "HVS07"},
    {"label": "Haringvlietsluizen sch 8", "value": "HVS08"},
    {"label": "Haringvlietsluizen sch 9", "value": "HVS09"},
    {"label": "Haringvlietsluizen sch 10", "value": "HVS10"},
    {"label": "Haringvlietsluizen sch 11", "value": "HVS11"},
    {"label": "Haringvlietsluizen sch 12", "value": "HVS12"},
    {"label": "Haringvlietsluizen sch 13", "value": "HVS13"},
    {"label": "Haringvlietsluizen sch 14", "value": "HVS14"},
    {"label": "Haringvlietsluizen sch 15", "value": "HVS15"},
    {"label": "Haringvlietsluizen sch 16", "value": "HVS16"},
    {"label": "Haringvlietsluizen sch 17", "value": "HVS17"},
    {"label": "IJgeul", "value": "IJGL"},
    {"label": "IJmuiden Buitenhaven", "value": "IJMH"},
    {"label": "IJmuiden Noordersluis O", "value": "IJMO"},
    {"label": "IJmuiden Noordersluis W", "value": "IJMW"},
    {"label": "IJsselkop", "value": "IJSS"},
    {"label": "IJmuiden Zuid havenhoofd", "value": "IJZ1"},
    {"label": "J6 platform", "value": "J6"},
    {"label": "K13 Alpha", "value": "K13"},
    {"label": "K13 Alpha 3", "value": "K133"},
    {"label": "K14 platform", "value": "K14"},
    {"label": "Kadoelen", "value": "KADL"},
    {"label": "Kaapduinen", "value": "KADU"},
    {"label": "Kallo", "value": "KALO"},
    {"label": "Kamperhoek", "value": "KAMH"},
    {"label": "Kampen", "value": "KAMP"},
    {"label": "Katsberg boven", "value": "KATB"},
    {"label": "Katsberg beneden", "value": "KATO"},
    {"label": "Kats Zandkreeksluis", "value": "KATS"},
    {"label": "Katerveer", "value": "KATV"},
    {"label": "Kinderdijk NAP -5m", "value": "KDD50"},
    {"label": "Keeten boei", "value": "KEET"},
    {"label": "Keizersveer", "value": "KEIZ"},
    {"label": "Keteldiep", "value": "KETD"},
    {"label": "Ketelhaven", "value": "KETH"},
    {"label": "Sluiskil brug", "value": "KGTB"},
    {"label": "Sluiskil brug (b)", "value": "KGTBb"},
    {"label": "Sluiskil brug (o)", "value": "KGTBo"},
    {"label": "Sas van Gent", "value": "KGTS"},
    {"label": "Sas van Gent (b)", "value": "KGTSb"},
    {"label": "Sas van Gent (o)", "value": "KGTSo"},
    {"label": "KrammersluisOZ1b -1.5mWS", "value": "KO1b"},
    {"label": "KrammersluisOZ1mb -3.5mWS", "value": "KO1m"},
    {"label": "KrammersluisOZ1m -2.5mWS", "value": "KO1mb"},
    {"label": "KrammersluisOZ1mo -4.5mWS", "value": "KO1mo"},
    {"label": "KrammersluisOZ1o -5.5mWS", "value": "KO1o"},
    {"label": "Kornwerderzand binnen", "value": "KOBI"},
    {"label": "Kornwerderzand buiten", "value": "KOBU"},
    {"label": "Kornwerderzand buiten zui", "value": "KOBU1"},
    {"label": "Kornwerderzand buiten noo", "value": "KOBU2"},
    {"label": "Kwdznd Mg b(-2mWS)", "value": "KOMb"},
    {"label": "Kwdznd Mg mb(-5mWS)", "value": "KOMmb"},
    {"label": "Kwdznd Mg mo(-6mWS)", "value": "KOMmo"},
    {"label": "Kwdznd mg o(-7mWS)", "value": "KOMo"},
    {"label": "Kwdznd sp b(-1,5mNAP)", "value": "KOSb"},
    {"label": "Kwdznd sp m(-6mNAP)", "value": "KOSm"},
    {"label": "Kwdznd sp mb(-4,5mNAP)", "value": "KOSmb"},
    {"label": "Kwdznd sp mo(-10,25mNAP)", "value": "KOSmo"},
    {"label": "Kwdznd sp o(-12mNAP)", "value": "KOSo"},
    {"label": "Kwdznd vg b(-2mNAP)", "value": "KOVb"},
    {"label": "Kwdznd vg mb(-5mNAP)", "value": "KOVmb"},
    {"label": "Kwdznd vg mo(-7mNAP)", "value": "KOVmo"},
    {"label": "Kwdznd vg o(-8,5mNAP)", "value": "KOVo"},
    {"label": "Krammerput Boven -1,5m", "value": "KPTb"},
    {"label": "Krammerput Midden_b -8,0m", "value": "KPTmb"},
    {"label": "Krammerput Midden_o -10,0", "value": "KPTmo"},
    {"label": "Krammerput Onder -15,0m", "value": "KPTo"},
    {"label": "Kier 1B WP08 -2mWS", "value": "KR1b"},
    {"label": "Kier 1M WP08 -11mWS", "value": "KR1m"},
    {"label": "Kier 1O WP08 -14,5mWS", "value": "KR1o"},
    {"label": "Kier 2B WP11 -2mWS", "value": "KR2b"},
    {"label": "Kier 2M WP11 -8mWS", "value": "KR2m"},
    {"label": "Kier 2O WP11 -13mWS", "value": "KR2o"},
    {"label": "Kier 3B WP10 -2mWS", "value": "KR3b"},
    {"label": "Kier 3M WP10 -9mWS", "value": "KR3m"},
    {"label": "Kier 3O WP10 -16mWS", "value": "KR3o"},
    {"label": "KIER 4B WP12 -10mWS", "value": "KR4b"},
    {"label": "KIER 4M WP12 -11mWS", "value": "KR4m"},
    {"label": "KIER 4O WP12 -12mWS", "value": "KR4o"},
    {"label": "Krabbersgat Noord", "value": "KRAN"},
    {"label": "Krabbersgat Zuid", "value": "KRAZ"},
    {"label": "Krammer Laagbekken  (b)", "value": "KRBLb"},
    {"label": "Krammer Laagbekken (o)", "value": "KRBLo"},
    {"label": "Krimpen a/d Lek", "value": "KRIL"},
    {"label": "Krimpen a/d IJssel", "value": "KRIY"},
    {"label": "Krammer Noord", "value": "KRND"},
    {"label": "Krammersluizen West", "value": "KRSL"},
    {"label": "Krimpen IJssel NAP -4.0m", "value": "KRY40"},
    {"label": "Krimpen IJssel NAP -5.5m", "value": "KRY55"},
    {"label": "Krammersluis volkerakzijd", "value": "KV1b"},
    {"label": "Krammersluis volkerakzijd", "value": "KV1o"},
    {"label": "Krammersluis volkerakzijd", "value": "KV2b"},
    {"label": "Krammersluis volkerakzijd", "value": "KV2o"},
    {"label": "Kleine Zalm", "value": "KZLM"},
    {"label": "L9 platform", "value": "L9"},
    {"label": "Lanaken", "value": "LANAK"},
    {"label": "Lauwersoog", "value": "LAUW"},
    {"label": "Lemmer Boezem", "value": "LBOE"},
    {"label": "Leeuwarden", "value": "LEEU"},
    {"label": "Lichteiland Goeree", "value": "LEG"},
    {"label": "Lekhaven NAP -2.5m", "value": "LEK25"},
    {"label": "Lekhaven NAP -5.0m", "value": "LEK50"},
    {"label": "Lekhaven NAP -7.0m", "value": "LEK70"},
    {"label": "Lemmer", "value": "LEMM"},
    {"label": "Lage Licht", "value": "LGL1"},
    {"label": "Liefkenshoek", "value": "LIEF"},
    {"label": "Lemmer IJsselmeer", "value": "LIJM"},
    {"label": "Linne boven", "value": "LINB"},
    {"label": "Linne beneden", "value": "LINN"},
    {"label": "Lith boven", "value": "LITB"},
    {"label": "Lith Dorp", "value": "LITO"},
    {"label": "Inlaat Landsweijer", "value": "LNDW"},
    {"label": "Lobith Haven", "value": "LOBH"},
    {"label": "Lobith", "value": "LOBI"},
    {"label": "Lobith", "value": "LOBM"},
    {"label": "Looveer Huissen", "value": "LOOV"},
    {"label": "Loozen", "value": "LOOZ"},
    {"label": "Lemmer Teroelsterkolk", "value": "LTER"},
    {"label": "Teroelsterkolk buiten", "value": "LTRY"},
    {"label": "Lemmer Woudagemaal", "value": "LWOU"},
    {"label": "Maaseik", "value": "MAAE"},
    {"label": "Maarssen", "value": "MAAR"},
    {"label": "Maassluis", "value": "MAAS"},
    {"label": "sluis Makkum buiten -130", "value": "MAKBb"},
    {"label": "sluis Makkum buiten -180", "value": "MAKBo"},
    {"label": "Marknesse", "value": "MARK"},
    {"label": "Markelose brug", "value": "MARKB"},
    {"label": "Meeswijk veer", "value": "MEESW"},
    {"label": "Megen", "value": "MEGE"},
    {"label": "Meppelerdiep km 2.5", "value": "MEP25"},
    {"label": "Middelharnis MB NAP -2m", "value": "MH020"},
    {"label": "Middelharnis MB NAP -8m", "value": "MH080"},
    {"label": "Middelharnis MB NAP -15m", "value": "MH150"},
    {"label": "Millingen a/d Rijn", "value": "MILL"},
    {"label": "Marina Kralendijk boven", "value": "MKRAb"},
    {"label": "Marina Kralendijk onder", "value": "MKRAo"},
    {"label": "Middelste Kievitswaard", "value": "MKWD"},
    {"label": "Maeslantkering zeezijde N", "value": "MLK1"},
    {"label": "Maeslantkering zeezijde Z", "value": "MLK2"},
    {"label": "Maeslantkering geleidetor", "value": "MLKZ"},
    {"label": "Maasgeul Maasvlakte Noord", "value": "MMND"},
    {"label": "Maasmond Papegaaiebek", "value": "MMPB"},
    {"label": "Monding Nieuwe Haven", "value": "MNHV"},
    {"label": "Moerdijkbrug 000", "value": "MO000"},
    {"label": "Moerdijkbrug 015", "value": "MO015"},
    {"label": "Moerdijkbrug 030", "value": "MO030"},
    {"label": "Moerdijkbrug 045", "value": "MO045"},
    {"label": "Moerdijkbrug 060", "value": "MO060"},
    {"label": "Moerdijkbrug 075", "value": "MO075"},
    {"label": "Moerdijkbrug 090", "value": "MO090"},
    {"label": "Moerdijkbrug 105", "value": "MO105"},
    {"label": "Moerdijkbrug 120", "value": "MO120"},
    {"label": "Moerdijkbrug 135", "value": "MO135"},
    {"label": "Moerdijkbrug 150", "value": "MO150"},
    {"label": "Moerdijkbrug 165", "value": "MO165"},
    {"label": "Moerdijkbrug 180", "value": "MO180"},
    {"label": "Moerdijkbrug 195", "value": "MO195"},
    {"label": "Moerdijkbrug 210", "value": "MO210"},
    {"label": "Moerdijkbrug 225", "value": "MO225"},
    {"label": "Moerdijkbrug 240", "value": "MO240"},
    {"label": "Moerdijkbrug 255", "value": "MO255"},
    {"label": "Moerdijkbrug 270", "value": "MO270"},
    {"label": "Moerdijkbrug 285", "value": "MO285"},
    {"label": "Moerdijkbrug 300", "value": "MO300"},
    {"label": "Moerdijk", "value": "MOER"},
    {"label": "Mond der Vecht", "value": "MOND"},
    {"label": "Marollegat", "value": "MRG"},
    {"label": "Marollegat (b)", "value": "MRGb"},
    {"label": "Marollegat (o)", "value": "MRGo"},
    {"label": "Mauriksewetering", "value": "MRSW"},
    {"label": "Muiden brug", "value": "MUIB"},
    {"label": "IJgeul Munitiestort 1", "value": "MUN1"},
    {"label": "IJgeul Munitiestort 2", "value": "MUN2"},
    {"label": "Maasvlakte Slufter", "value": "MVSL"},
    {"label": "Naviduct Noord", "value": "NAVN"},
    {"label": "Naviduct Zuid", "value": "NAVZ"},
    {"label": "NDSM-werf (o)", "value": "NDS1"},
    {"label": "NDSM-werf (b)", "value": "NDS2"},
    {"label": "Neer", "value": "NEER"},
    {"label": "Negenoord-Oost", "value": "NEGO"},
    {"label": "Negenoord-West", "value": "NEGW"},
    {"label": "Nes", "value": "NES"},
    {"label": "Nes 2 (golven)", "value": "NES2"},
    {"label": "Nieuw Beerta", "value": "NIBE"},
    {"label": "Nijmegen haven", "value": "NIJM"},
    {"label": "Nijkerk Oost", "value": "NIJO"},
    {"label": "Nijkerk West", "value": "NIJW"},
    {"label": "Nelson platform1", "value": "NLS1"},
    {"label": "ADM Noordervaart", "value": "NVAA"},
    {"label": "Nieuwegein", "value": "NWGN"},
    {"label": "Nieuwe Statenzijl", "value": "NWST"},
    {"label": "Den Oever binnen", "value": "OEBI"},
    {"label": "Den Oever buiten", "value": "OEBU"},
    {"label": "Hengelo Oelerbrug", "value": "OELB"},
    {"label": "Den Oever sp b(-1,5mWS)", "value": "OESb"},
    {"label": "Den Oever sp mb(-4,5mWS)", "value": "OESmb"},
    {"label": "Den Oever sp mo(-5,6mWS)", "value": "OESmo"},
    {"label": "Den Oever sp o(-6,7mWS)", "value": "OESo"},
    {"label": "Den Oever vg b(-2mNAP)", "value": "OEVb"},
    {"label": "Den Oever vg mb(-4mNAP)", "value": "OEVmb"},
    {"label": "Den Oever vg mo(-5,5mNAP)", "value": "OEVmo"},
    {"label": "Den Oever vg o(-7m NAP)", "value": "OEVo"},
    {"label": "Olst", "value": "OLST"},
    {"label": "Ommen Hesselmulertbrug", "value": "OMMH"},
    {"label": "Ommen Ommerkanaal", "value": "OMMK"},
    {"label": "Oosterschelde 11", "value": "OS11"},
    {"label": "Oosterschelde 11 (b)", "value": "OS11b"},
    {"label": "Oosterschelde 14", "value": "OS14"},
    {"label": "Oosterschelde 4", "value": "OS4"},
    {"label": "Oosterschelde 4 (b)", "value": "OS4b"},
    {"label": "Oosterschelde 4 (o)", "value": "OS4o"},
    {"label": "Oosterscheldeker. Hammen", "value": "OSKH"},
    {"label": "Oosterscheldeker. Roompot", "value": "OSKR"},
    {"label": "Oosterscheldeker. Schaar", "value": "OSKS"},
    {"label": "Oudeschild", "value": "OUDE"},
    {"label": "Ovl v Bosscherveld QH", "value": "OVB"},
    {"label": "Overloop van Hansweert", "value": "OVHA"},
    {"label": "Overloop v. Hansweert (b)", "value": "OVHAb"},
    {"label": "Overloop v. Hansweert gol", "value": "OVHW"},
    {"label": "Overloop van Valkenisse", "value": "OVVA"},
    {"label": "Oude Westereems Noordboei", "value": "OWEN"},
    {"label": "Oude Westereems Zuidboei", "value": "OWEZ"},
    {"label": "P11 platform", "value": "P11"},
    {"label": "Pannerdens kanaal", "value": "PANK"},
    {"label": "Pannerdense kop", "value": "PANN"},
    {"label": "Plazabeach Terminal", "value": "PBEA"},
    {"label": "Sint Pieter Noord 2", "value": "PIET"},
    {"label": "Plaat van Oude Tonge (b)", "value": "PLOTb"},
    {"label": "Plaat van Oude Tonge (o)", "value": "PLOTo"},
    {"label": "Poeldonk beneden - Aa", "value": "POEO"},
    {"label": "Pas van Terneuzen boei", "value": "PVT"},
    {"label": "Rak Noord", "value": "RAKN"},
    {"label": "Rak Zuid", "value": "RAKZ"},
    {"label": "Ramspolkering Ketelmeerzi", "value": "RAMK"},
    {"label": "Ramspolbrug", "value": "RAMS"},
    {"label": "Roermond boven temp", "value": "ROEB"},
    {"label": "Roermond boven", "value": "ROER"},
    {"label": "Roggenplaat", "value": "ROGP"},
    {"label": "Rotterdam Luchthaven", "value": "ROT1"},
    {"label": "Rotterdam Geulhaven", "value": "ROT2"},
    {"label": "Rotterdam", "value": "ROTT"},
    {"label": "Rozenburgse Sluis", "value": "ROZS"},
    {"label": "Beergat Radarpost 4", "value": "RP04"},
    {"label": "Caland West Radarpost 5", "value": "RP05"},
    {"label": "Caland Midden Radarpost 6", "value": "RP06"},
    {"label": "Rozenburg Radarpost 8", "value": "RP08"},
    {"label": "Geulhaven Radarpost 10", "value": "RP10"},
    {"label": "Waalhaven Radarpost 19", "value": "RP19"},
    {"label": "Kuip2 Radarpost 23", "value": "RP23"},
    {"label": "Caland Oost Radarpost 32", "value": "RP32"},
    {"label": "Roompot binnen (SVKO)", "value": "RPBI"},
    {"label": "Roompot buiten (SVKO)", "value": "RPBU"},
    {"label": "Roompotsluis (SVKO)", "value": "RPSL"},
    {"label": "Rijswijk Betuwepand", "value": "RSWK"},
    {"label": "Rotem Maas", "value": "RTEM"},
    {"label": "Rotem Bichterweerd", "value": "RTMB"},
    {"label": "Reevesluis noord", "value": "RVN"},
    {"label": "Reevesluis zuid", "value": "RVZ"},
    {"label": "Randzelgat Noord boei", "value": "RZGN1"},
    {"label": "Sluis 4 boven", "value": "S04B"},
    {"label": "Sluis 4 beneden", "value": "S04O"},
    {"label": "Sluis 5 boven", "value": "S05B"},
    {"label": "Sluis 5 beneden", "value": "S05O"},
    {"label": "Sluis 6 boven", "value": "S06B"},
    {"label": "Sluis 6 beneden", "value": "S06O"},
    {"label": "Sluis 7 spuiduiker", "value": "S07S"},
    {"label": "Sluis 9 boven", "value": "S09B"},
    {"label": "Sluis 9 spuiduiker", "value": "S09S"},
    {"label": "Sluis 10 boven", "value": "S10B"},
    {"label": "Sluis 10 beneden", "value": "S10O"},
    {"label": "Sluis 11 boven", "value": "S11B"},
    {"label": "Sluis 11 beneden", "value": "S11O"},
    {"label": "Sluis 12 boven", "value": "S12B"},
    {"label": "Sluis 12 beneden", "value": "S12O"},
    {"label": "Sluis 13", "value": "S131"},
    {"label": "Sluis 13 ADM", "value": "S13A"},
    {"label": "Sluis 13 boven", "value": "S13B"},
    {"label": "Sluis 13 beneden", "value": "S13O"},
    {"label": "Sluis 15 boven", "value": "S15B"},
    {"label": "Sluis 15 voedingskanaal", "value": "S15V"},
    {"label": "Sluis 16 boven", "value": "S16B"},
    {"label": "Sluis 16 beneden", "value": "S16O"},
    {"label": "Sluis 21 boven", "value": "S21B"},
    {"label": "Sluis 21 spuikanaal", "value": "S21S"},
    {"label": "Sluis 22 boven", "value": "S22B"},
    {"label": "Sluis 22 beneden", "value": "S22O"},
    {"label": "Sluis 23 boven", "value": "S23B"},
    {"label": "Sluis 23 beneden", "value": "S23O"},
    {"label": "Sluis 24 boven", "value": "S24B"},
    {"label": "Sluis 24 beneden", "value": "S24O"},
    {"label": "Sluis 24 spuikanaal", "value": "S24S"},
    {"label": "Sambeek boven", "value": "SAMB"},
    {"label": "Sambeek beneden", "value": "SAMO"},
    {"label": "Schabbert boven", "value": "SCAB"},
    {"label": "Schabbert beneden", "value": "SCAO"},
    {"label": "Scheveningen", "value": "SCHE"},
    {"label": "Schoonhoven", "value": "SCHH"},
    {"label": "Schiermonnikoog", "value": "SCHI"},
    {"label": "Schaar Stroomgat", "value": "SCHS"},
    {"label": "Schellingwouderbrug", "value": "SCHWB"},
    {"label": "Scheeresluis beneden", "value": "SCSO"},
    {"label": "Schulpengat", "value": "SGAT"},
    {"label": "Sluis Helmond boven", "value": "SHMB"},
    {"label": "Sint Pieter noord", "value": "SINT"},
    {"label": "Slaak Noord boven", "value": "SKNDb"},
    {"label": "Slaak Noord midden", "value": "SKNDm"},
    {"label": "Slaak Noord onder", "value": "SKNDo"},
    {"label": "Slaak Oost", "value": "SKOT"},
    {"label": "Slaak Zuid", "value": "SKZD"},
    {"label": "Slochtersluis boven", "value": "SLBV"},
    {"label": "Zwartsluis gemaal pomp mi", "value": "SLGPM"},
    {"label": "Zwartsluis gemaal pomp O", "value": "SLGPO"},
    {"label": "Zwartsluis gemaal pomp W", "value": "SLGPW"},
    {"label": "Marksluis boven - WHK", "value": "SMAB"},
    {"label": "Marksluis beneden - Mark", "value": "SMAO"},
    {"label": "Smeermaas", "value": "SMEE"},
    {"label": "Schiermonnikoog Noord boe", "value": "SMN1"},
    {"label": "Schiermonnikoog Westgat b", "value": "SMWG"},
    {"label": "Spuisluis Oude Eemskanaal", "value": "SOEB"},
    {"label": "Spaarnd.polder NAP -1.4m", "value": "SPA14"},
    {"label": "Spaarnd.polder NAP -6.4m", "value": "SPA64"},
    {"label": "Spooldersluis binnen", "value": "SPBI"},
    {"label": "Spijkenisserbrug West", "value": "SPBR"},
    {"label": "Stroommeetpaal Eemshaven", "value": "SPE"},
    {"label": "Panheel boven - ZWV", "value": "SPHB"},
    {"label": "Spijkenisserbrug NAP-2.5m", "value": "SPI25"},
    {"label": "Spijkenisserbrug NAP-4.5m", "value": "SPI45"},
    {"label": "Spijkenisserbrug NAP-9.0m", "value": "SPI90"},
    {"label": "Spijkenisse", "value": "SPIJ"},
    {"label": "Spaanjerd", "value": "SPNJD"},
    {"label": "Middelharnis Spui NAP -1m", "value": "SPU10"},
    {"label": "Middelharnis Spui NAP -5m", "value": "SPU50"},
    {"label": "Bathse spuikanaal Inloop", "value": "SPUI"},
    {"label": "Bathse spuikan. Inloop (b", "value": "SPUIb"},
    {"label": "Bathse spuikan. Inloop (o", "value": "SPUIo"},
    {"label": "IJgeul stroommeetpaal", "value": "SPY"},
    {"label": "IJgeul SMP 2 (bus)", "value": "SPY2"},
    {"label": "Sluis Schijndel boven", "value": "SSHB"},
    {"label": "Sluis Schijndel beneden", "value": "SSHO"},
    {"label": "Sluis Schijndel spuik", "value": "SSHS"},
    {"label": "Scheepstal", "value": "SSTL"},
    {"label": "Sint Annaland", "value": "STAN"},
    {"label": "Stavenisse", "value": "STAV"},
    {"label": "Stellendam binnen WS-2m", "value": "STB02"},
    {"label": "Stellendam binnen WS-6m", "value": "STB06"},
    {"label": "Stellendam binnen WS-11m", "value": "STB11"},
    {"label": "Stellendam buiten boven", "value": "STBUb"},
    {"label": "Stellendam buiten onder", "value": "STBUo"},
    {"label": "De Steeg", "value": "STEE"},
    {"label": "Stellendam buiten", "value": "STEL"},
    {"label": "Stevensweert", "value": "STEV"},
    {"label": "Steurgat", "value": "STGT"},
    {"label": "Stortemelk boei", "value": "STM1"},
    {"label": "Stortemelk Oost", "value": "STMO1"},
    {"label": "Steenenmuur", "value": "STMR"},
    {"label": "Stavoren", "value": "STVO"},
    {"label": "Surinamekade", "value": "SURI"},
    {"label": "Schaar v/d Noord", "value": "SVDN"},
    {"label": "Schellingw.brug NAP -2.8m", "value": "SWB28"},
    {"label": "Texelhors", "value": "TEHO"},
    {"label": "Termunterzijl", "value": "TERM"},
    {"label": "Terneuzen", "value": "TERN"},
    {"label": "Terschelling Noordzee", "value": "TERS"},
    {"label": "Texel Noordzee", "value": "TEXE"},
    {"label": "Terherne Boezem Oostzijde", "value": "THBO"},
    {"label": "Terherne Boezem Westzijde", "value": "THBW"},
    {"label": "Tiel Kanaal", "value": "TIEK"},
    {"label": "Tiel Waal", "value": "TIEW"},
    {"label": "Tiel Waal (RAM)", "value": "TIEWB"},
    {"label": "Terneuzen Westsluis", "value": "TNWS"},
    {"label": "Inlaat Teersesluispolder", "value": "TPOL"},
    {"label": "Breda Trambrug", "value": "TRMB"},
    {"label": "Terneuzen Westsluis ZZ", "value": "TWZZ"},
    {"label": "Terneuzen Westsluis ZZ (b", "value": "TWZZb"},
    {"label": "Terneuzen Westsluis ZZ (o", "value": "TWZZo"},
    {"label": "Trintelzand", "value": "TZND"},
    {"label": "Trintelzand boven", "value": "TZNDb"},
    {"label": "Trintelzand onder", "value": "TZNDo"},
    {"label": "Uithuizerwad 2", "value": "UHW2"},
    {"label": "Uithuizerwad 3", "value": "UHW3"},
    {"label": "Uithuizerwad", "value": "UHWD"},
    {"label": "Uikhoven", "value": "UIKHV"},
    {"label": "Vechterweerd beneden", "value": "VECO"},
    {"label": "Veessen - Wapenveld", "value": "VEES"},
    {"label": "Venlo", "value": "VENL"},
    {"label": "Volkerakgat 2", "value": "VG02"},
    {"label": "Volkerakgat 3", "value": "VG03"},
    {"label": "Volkerak Galathee", "value": "VK"},
    {"label": "Volkerak Galathee (b)", "value": "VKb"},
    {"label": "Volkerak Galathee (o)", "value": "VKo"},
    {"label": "Vlaardingen", "value": "VLAA"},
    {"label": "Vlieland", "value": "VLI1"},
    {"label": "Vlieland haven", "value": "VLIE"},
    {"label": "Vlissingen", "value": "VLIS"},
    {"label": "Velserkom b WS3", "value": "VLSKb"},
    {"label": "Velserkom m WS3", "value": "VLSKm"},
    {"label": "Velserkom o WS3", "value": "VLSKo"},
    {"label": "VM3 Zandkreeksluis", "value": "VM3"},
    {"label": "Veersemeer 4 Oranjeplaat", "value": "VM4"},
    {"label": "VM4 Oranjeplaat (b)", "value": "VM4b"},
    {"label": "VM4 Oranjeplaat (o)", "value": "VM4o"},
    {"label": "Veersemeer 5 Schotsman", "value": "VM5"},
    {"label": "VM5 Schotsman (b)", "value": "VM5b"},
    {"label": "VM5 Schotsman (o)", "value": "VM5o"},
    {"label": "Volkerak Noord (b)", "value": "VOLKb"},
    {"label": "Volkerak Noord (o)", "value": "VOLKo"},
    {"label": "Vossenbeemd Helmond", "value": "VOSB"},
    {"label": "Nieuw Vossemeer", "value": "VOSM"},
    {"label": "Nieuw Vossemeer (b)", "value": "VOSMb"},
    {"label": "Nieuw Vossemeer (o)", "value": "VOSMo"},
    {"label": "Vlakte v/d Raan", "value": "VR"},
    {"label": "Vlakte v/d Raan (b)", "value": "VRb"},
    {"label": "Vlakte v/d Raan (o)", "value": "VRo"},
    {"label": "Vuren", "value": "VURE"},
    {"label": "Vogelenzang", "value": "VZNG"},
    {"label": "Walsoorden", "value": "WALS"},
    {"label": "Weesp", "value": "WEES"},
    {"label": "Well Dorp", "value": "WELL"},
    {"label": "Westereems Oost boei", "value": "WEO1"},
    {"label": "Werkendam buiten", "value": "WERK"},
    {"label": "Westervoort", "value": "WEST"},
    {"label": "Westervoort IJsseldijkerw", "value": "WESTV"},
    {"label": "Inlaat Weurt", "value": "WEUR"},
    {"label": "Westereems West boei", "value": "WEW1"},
    {"label": "Wieldrecht", "value": "WIED"},
    {"label": "Wielingen Noord", "value": "WIEL"},
    {"label": "Wierumergronden", "value": "WIER"},
    {"label": "Wijdenes", "value": "WIJD"},
    {"label": "Wijhe", "value": "WIJH"},
    {"label": "Wijk bij Duurstede", "value": "WIJK"},
    {"label": "Wijk aan Zee", "value": "WIJZ"},
    {"label": "Wilhelminadorp", "value": "WILH"},
    {"label": "Westkapelle", "value": "WKAP"},
    {"label": "Waalwijk", "value": "WLWK"},
    {"label": "West-Terschelling", "value": "WTER"},
    {"label": "Yerseke", "value": "YE"},
    {"label": "Zaltbommel", "value": "ZALT"},
    {"label": "Zeelandbrug wind", "value": "ZBWI"},
    {"label": "Zijkanaal C (NAP -140)", "value": "ZC14"},
    {"label": "Zijkanaal C (NAP -440)", "value": "ZC44"},
    {"label": "Zandkreekdam", "value": "ZKD"},
    {"label": "Zandkreekdam OS", "value": "ZKO"},
    {"label": "Zandkreekdam VM", "value": "ZKV"},
    {"label": "Zutphen Noord", "value": "ZUTP"},
    {"label": "Zwartsluis buiten", "value": "ZWBU"},
]